### ISSUE TITLE
Not all classes get applied

### ISSUE THREAD

**Issue by teds31** [svelte-add/svelte-add#111]
Have an interesting issue, which I at the moment with Vite, I believe is causing some interference with some utility classes being applied incorrectly, whether it's based on responsiveness or something else, such as the blur effect. 

`    .ctaSlice {
        @apply text-white mt-32 md:ml-8 xl:mt-72 xl:ml-24 macAir:ml-48 2xl:ml-60 3xl:ml-66 4xl:mx-auto;
    }`

`  .titleSlice {
        @apply w-7/10 md:w-3/5 xl:w-2/5 2xl:w-1/3 3xl:w-3/10 mb-2 4xl:w-full;
    }`

With the example above and here we have an example where the 2xl (which is a custom screen size I added in my config) gets applied most of the time, but randomly picks and chooses which utility class to render based on the size. So for example my `macAir:ml-48` will apply but when I get to a screen size of `2xl`, it doesn't use that class, but for another component, like in `titleSlice`, that will render on that screen size. It randomly picks and chooses which utilities to use and it can be frustrating. No way to clear cache I don't think with SvelteKit and this can happen on different browsers, or even using Sizzy. 

I am not sure if there is a missing configuration with Vite and tailwindcss for the critical CSS configuration and it's not a deal-breaker as you can still continue using regular CSS, but then you lose some of the pros of tailwind for responsiveness.

**Comment by babichjacob** [comment]
I suspect this issue has been resolved by now because of inactivity. Please comment here (and I'll re-open the issue) or open a new issue if there's any reproduction for the issue.
