### ISSUE TITLE
ESLint is upset by the mdsvex import

### ISSUE THREAD

**Issue by BryanSchuetz** [svelte-add/svelte-add#118]
On a fresh install:

`npm init svelte@next`
`npm install`
`npx svelte add mdsvex`
`npm install`
`npm run dev`

The following error is returned when requesting the `/example-markdown` route: "Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .md file format."

**Comment by babichjacob** [comment]
Is this still a problem, or has the ecosystem improved and solved it?

**Comment by babichjacob** [comment]
Running `npm run lint` on a freshly initialized SvelteKit + mdsvex project does not reveal any errors, so I will assume it has been resolved by updates to the programs involved over the past few months.
