### ISSUE TITLE
Add a `variables.scss` file that we add to every Svelte component's style block with `prependData`

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/svelte-add#126]
This is a common question I see on Discord so it would be best to solve it for everyone instead of vaguely gesturing in the direction. It would also teach me how it works.

Comments, suggestions, and / or demonstrations of how you (the reader) do it in your app would be appreciated. I anticipate difficulty with paths / aliases.

**Comment by Myrmod** [comment]
It's the same for LESS and the far superior Stylus

```js
preprocess: sveltePreprocess({
    sourceMap: true,
    scss: {
      prependData: '@import "src/styles/prepend.scss"',
    },
  }),
```

`prependData` is a string that will be added to your style tag or files. Paths inside will be resolved automatically.

For reference a solution with just vite would be

```js
css: {
  preprocessorOptions: {
    scss: {
      additionalData: `
        @use 'sass:math';
        @import "./src/styles/functions";
      `,
    },
  },
},
```

**Comment by babichjacob** [comment]
Got this information from a trusted source (GrygrFlzr):

if you want to access scss vars and mixins adjust your svelte.config.js to use prependData
```
import preprocess from 'svelte-preprocess';

const config = {
  preprocess: preprocess({
    scss: {
      prependData: `@import "src/global.scss";`
    },
  })
}

export default config;
```

**Comment by babichjacob** [comment]
Closed by https://github.com/svelte-add/scss/commit/db8086768d70954a89168a883b307699ce9ff7b0

Thank you!
