### ISSUE TITLE
Conditional classes like for a navigation bar

### ISSUE THREAD

**Issue by georgedalai** [svelte-add/svelte-add#129]
I am trying to create an active state for the navigation bar based on the sveltekit docs but it doesn't work with tailwind. Do you have any suggestions?

**Comment by babichjacob** [comment]
Check out an example `__layout.svelte` like this to start from:

```svelte
<script>
	import "../app.postcss";
	
	import { page } from "$app/stores";
</script>

<nav>
	<a href="/a" class:bg-blue-400={$page.path === "/a"}>Page a</a>
	<a href="/b" class:bg-blue-400={$page.path === "/b"}>Page b</a>
</nav>

<slot></slot>
```

I've tested it and it works in both dev and prod without the styles being wrongly removed.
