### ISSUE TITLE
Maybe missing some extractor config on tailwindcss adder

### ISSUE THREAD

**Issue by outerlook** [svelte-add/svelte-add#130]
Hi! I was having some problems with `@apply` and `@layer X` definitions with an app that used a config similar to this adder.

I was able to fix that with 
```typescript
// tailwind.config.js
module.exports = {
  purge: {
    options: {
	  content: ['./src/**/*.{html,js,svelte,ts}'],
      defaultExtractor: content => [
        ...(content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || []),
        ...(content.match(/(?<=class:)[^=>\/\s]*/g) || []),
      ],
    },
  },
```

but I don't fully understand how exactly it fixes. I don't mind pushing a PR, but for the reason I don't dominate it very well yet, first I would like to open a issue to discover if it would be against something this repo aims to accomplish...

Thanks.

https://github.com/svelte-add/tailwindcss/blob/1de342a1e483b821f0ed8abf5f939693ef5728aa/__run.js#L40

**Comment by babichjacob** [comment]
Can you share a repository that shows the issue being present before making this change, that then shows the issue is resolved once the change is made?

**Comment by babichjacob** [comment]
Since https://github.com/svelte-add/tailwindcss/commit/e20fd99556ae8e6289e4fb1eb86ca786dc4afdc1, there is no longer a custom extractor specified because the option for AOT was removed because it will be removed in Tailwind 3.
