### ISSUE TITLE
Allow to add tailwindcss and SCSS to the same project 

### ISSUE THREAD

**Issue by TheOnlyTails** [svelte-add/svelte-add#132]
Currently, you cannot add tailwindcss and SCSS together, because tailwindcss requires postcss to function.

However, it's possible to use [postcss/postcss-scss](github.com/postcss/postcss-scss) to support SCSS syntax in PostCSS.

I suggest that if the `svelte-add` command is called with both tailwindcss and SCSS, instead of adding the regular SCSS config, it'll add it with `postcss-scss` syntax.

**Comment by canadaduane** [comment]
Would this allow a svelte component to take advantage of both tailwindcss in "class" attributes on HTML, as well as CSS defined inside a component's `<style />` tag? e.g.

```
<div class="lg:text-3xl custom">Hello World</div>

<style>
.custom {
  color: red;
}
</style>
```

**Comment by babichjacob** [comment]
> Would this allow a svelte component to take advantage of both tailwindcss in "class" attributes on HTML, as well as CSS defined inside a component's `<style />` tag? e.g.
> 
> ```
> <div class="lg:text-3xl custom">Hello World</div>
> 
> <style>
> .custom {
>   color: red;
> }
> </style>
> ```

This sample already works. Did you have a more complicated example in mind, because I don't personally see how SCSS relates?

**Comment by TheOnlyTails** [comment]
> Would this allow a svelte component to take advantage of both tailwindcss in "class" attributes on HTML, as well as CSS defined inside a component's `<style />` tag? 

Yes. PostCSS-SCSS simply adds SCSS syntax to PostCSS. Nothing more.

**Comment by canadaduane** [comment]
> This sample already works. Did you have a more complicated example in mind, because I don't personally see how SCSS relates?

You're right, my mistake.

**Comment by babichjacob** [comment]
While it's not officially supported / deliberately programmed to work, it actually works to start the project with Tailwind CSS then add SCSS after the fact:


```sh
npm init --yes @svelte-add/kit@latest my-new-app -- --with tailwindcss
# or just postcss if you don't want Tailwind

npx svelte-add@latest scss
``` 

This is just an accident from https://github.com/svelte-add/svelte-add/issues/137#issuecomment-909614362, so I am sorry if it ever stops working.

**Comment by AdrianGonz97** [comment]
We currently don't have the `scss` adder anymore, and I don't think we have any plans on adding it back anytime soon. Closing
