### ISSUE TITLE
Add Storybook

### ISSUE THREAD

**Issue by frederikhors** [svelte-add/svelte-add#133]
What about Storybook?

**Comment by babichjacob** [comment]
Notes:
* https://imfeld.dev/writing/sveltekit_with_storybook

**Comment by oneezy** [comment]
Definitely need this one!

**Comment by Nilmanduil** [comment]
Working on it 😉

**Comment by benmccann** [comment]
There's `npx sb init` which does the same thing (although it doesn't currently work). Maybe we should just contribute to that

I opened a tracking issue for a number of issues I'm trying to fix for improved Storybook support: https://github.com/sveltejs/kit/issues/5397

**Comment by babichjacob** [comment]
Reopening to track making Storybook selectable during the interactive app creation process / as `storybook` on the command line (wrapping their command)

**Comment by manuel3108** [comment]
We have such an adder in place now: https://svelte-add.com/adder/storybook
