### ISSUE TITLE
Licences of submoduls

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-add#141]
Disclaimer: Im not an expert.

I have just seen that, all the repos that were added as submodules do not contain any licence information.
I think we should at least mention them in the readme, or create licence files in the other repos as well.

**Comment by babichjacob** [comment]
I've added a license to all the adders originally written by me. We can close this issue once you add a license to the Bulma adder wherein you're the copyright owner.

**Comment by manuel3108** [comment]
Done. Closing.

**Comment by babichjacob** [comment]
Thank you!!
