### ISSUE TITLE
Generate READMEs (including usage, options, and issue links) for all adders

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-add#147]
Build-in adders currently do have the issue tab disabled, which is a good thing in my opinion.

But people don't know where they should post their problems or ideas atm, when they are visiting any of the built-in adder.
I would suggest to add something simmilar to the readme:

# ❓ Need help?
If you need any help or want to share your feedback, please provide it in the main `svelte-add` repository. [Create an issue here](https://github.com/svelte-add/svelte-add/issues/new)

**Comment by babichjacob** [comment]
Good idea. The current note 
> This is an adder for `svelte-add`; you should [read its `README`](https://github.com/svelte-add/svelte-add#readme) before continuing here.

might not make issues as discoverable as they should be.

**Comment by manuel3108** [comment]
I have just done so for the bulma adder.

While during that I thought that we might need to rework the readmes completely, as they i.e. don't reference the possibiliy to create a new svelte-kit app with the selection you implemented. Also they are missing the syntax with the `npx svelte-add@latest --with bulma` (or something like that)

But on the other hand, that might be too much information. What are your thoughts about that?

**Comment by manuel3108** [comment]
This is generally done. We might need to improve the script in some places, see #219  #269
