### ISSUE TITLE
Problems implementing PostCss

### ISSUE THREAD

**Issue by JappIC** [svelte-add/svelte-add#150]
Hello, I did the steps to integrate PostCss but when I try to work with my module using PostCss syntax it sends me the following error.

```
[!] (plugin svelte) ParseError: Identifier is expected
src\layout\CardData.svelte
50:         align-items: center;
51:
52:         & img {
             ^
53:             color: red
54:         }
ParseError: Identifier is expected
    at error (C:\Users\Admin\Documents\GitHub\Facturapp\node_modules\svelte\src\compiler\utils\error.ts:25:16)
    at Parser$1.error (C:\Users\Admin\Documents\GitHub\Facturapp\node_modules\svelte\src\compiler\parse\index.ts:101:3)
    at Object.read_style [as read] (C:\Users\Admin\Documents\GitHub\Facturapp\node_modules\svelte\src\compiler\parse\read\style.ts:31:11)  
    at tag (C:\Users\Admin\Documents\GitHub\Facturapp\node_modules\svelte\src\compiler\parse\state\tag.ts:189:27)
    at new Parser$1 (C:\Users\Admin\Documents\GitHub\Facturapp\node_modules\svelte\src\compiler\parse\index.ts:53:12)
    at parse (C:\Users\Admin\Documents\GitHub\Facturapp\node_modules\svelte\src\compiler\parse\index.ts:218:17)
    at compile (C:\Users\Admin\Documents\GitHub\Facturapp\node_modules\svelte\src\compiler\compile\index.ts:93:14)
    at Object.transform (C:\Users\Admin\Documents\GitHub\Facturapp\node_modules\rollup-plugin-svelte\index.js:111:21)
    at C:\Users\Admin\Documents\GitHub\Facturapp\node_modules\rollup\dist\shared\rollup.js:22620:25
[2021-10-01 12:25:16] waiting for changes...
```
### Style
```
<style lang="postcss">
    div{
        border: var(--border);
        display: grid;
        grid-template-columns: auto 1fr;
        align-items: center;

        & img {
            max-width: 150px;
            width: 100%;
        }
    }
</style>
```
Attached project link where the error happens in case you want to browse [Facturapp](https://github.com/JappIC/Facturapp). Use svelte

Thank you for your time and effort in making this tool.

**Comment by babichjacob** [comment]
Install the `postcss-nested` plugin and put it early in the list of PostCSS plugins in `postcss.config.cjs`

**Comment by JappIC** [comment]
I still get the same result after: 

1 Install
`npm install --save-dev postcss postcss-nested`

2 - Set up postcss.config.cjs 
```
const postcssNested = require ("postcss-nested");
const autoprefixer = require("autoprefixer");
const cssnano = require("cssnano");

const mode = process.env.NODE_ENV;
const dev = mode === "development";

const config = {
	plugins: [
        postcssNested(),
		autoprefixer(),

		!dev && cssnano({
			preset: "default",
		}),
	],
};

module.exports = config;
```

**Comment by babichjacob** [comment]
Oh! You're using Rollup, which [`svelte-add` doesn't support](https://github.com/svelte-add/svelte-add#-support-for-svelte-with-webpack-or-rollup).

Since your project doesn't have a custom Rollup config or anything like that, you can pretty quickly copy your Svelte files to a newly created Vite app with `npm init vite`. There is also [this video](https://www.youtube.com/watch?v=D66wC4VsgVU) as a reference. 

It may also work to instead add `const svelteConfig = require("./svelte.config.cjs")` to your Rollup config and add `...svelteConfig` [here](https://github.com/JappIC/Facturapp/blob/50bff4bfb40fae72c4d934b5f18710d400721b12/rollup.config.js#L41), but I would still recommend migrating to Vite.

**Comment by JappIC** [comment]
I guess another option is to install Sveltekit? That already integrates Vite

**Comment by babichjacob** [comment]
Yes, that is also a good option. I suggested regular Vite first because it's closer to the regular Rollup project you started with.

If you want to use SvelteKit, here's a command to initialize a minimal project with PostCSS that you can copy your `.svelte` files into:

```js
npm init --yes @svelte-add/kit@latest new-postcss-svelte-app -- --with postcss --demos false
```

**Comment by JappIC** [comment]
Thank you very much for the help

**Comment by babichjacob** [comment]
You're welcome! Thank you for your interest in the project.
