### ISSUE TITLE
Add Carbon-Components 

### ISSUE THREAD

**Issue by DaleCam** [svelte-add/svelte-add#152]
I would be sooooo grateful if someone could add IBMs  carbon components to this :)

**Comment by DaleCam** [comment]
Some helpful links:
https://github.com/carbon-design-system/carbon
and
https://github.com/carbon-design-system/carbon-components-svelte

**Comment by benmccann** [comment]
It's unclear to me that there's enough here worth having an adder. The setup isn't that involved. But the setup instructions are very long and confusing. I think it'd be better just to simplify the setup instructions of that package instead. I sent https://github.com/carbon-design-system/carbon-components-svelte/pull/1989 as a start
