### ISSUE TITLE
Tailwind CSS v3.0.0-alpha.1

### ISSUE THREAD

**Issue by babakfp** [svelte-add/svelte-add#153]
Hi
Add support for [Tailwind v3](https://github.com/tailwindlabs/tailwindcss/discussions/5668), please.
Thanks

**Comment by babichjacob** [comment]
Yup, I got the notification for the alpha release today and have been looking into it!

**Comment by babichjacob** [comment]
Closed by https://github.com/svelte-add/tailwindcss/commit/e20fd99556ae8e6289e4fb1eb86ca786dc4afdc1!

**Comment by babakfp** [comment]
Thank you so much for all your hard work❤️
