### ISSUE TITLE
Output of changes

### ISSUE THREAD

**Issue by AlexRMU** [svelte-add/svelte-add#157]
It would be nice after adding something to output a list of all changes to the console like git diff

**Comment by babichjacob** [comment]
I think this would be feature creep. We could instead document that you should make a git commit before running an adder on your existing project both for safety and so you can see what it does by comparing the changes to before the adder(s) ran (which also lets you see if / how it malfunctioned if your project is different from what `svelte-add` expects).

I think the command is `git log --patch` and / or you can use your IDE to look.
