### ISSUE TITLE
Sveltestrap over Bootstrap | Adder

### ISSUE THREAD

**Issue by billh93** [svelte-add/svelte-add#160]
Hey guys!

I have been a bootstrap user for years, so I'm quite familiar with it. However, I am new to svelte/sveltekit but instantly fell in love with how simple and fast it is to create web applications.

I've tried to use the current bootstrap adder ([Bootstrap](https://github.com/svelte-add/bootstrap)) and while it seems like it does work. I have to manually import the missing components inside the `app.scss` file like: 'nav', 'navbar', and 'dropdown' in order to use components that are not included.

I've been using [Sveltestrap](https://github.com/bestguy/sveltestrap) in another project prior to this and sveltestrap blows this bootstrap adder out of the water as it already has every component included you just have to included in the file you want to use it on.

Not only that, it is already supporting Bootstrap v5 with consistent updates to the project as it first initialized 2 years ago.

You can play around with the library at [Sveltestrap](https://sveltestrap.js.org/?path=/story/components--get-started).

**Comment by babichjacob** [comment]
Just published https://github.com/svelte-add/bootstrap/commit/f102810fc8895a0eb1aae5824177dd241dd4c189 to include more imports by default

**Comment by babichjacob** [comment]
We can add an option to install Sveltestrap too (since that relies on you providing the CSS which is what the Bootstrap adder currently does)

**Comment by babichjacob** [comment]
Also published https://github.com/svelte-add/bootstrap/tree/a2cf53aa092540867ffd517f42ad59c41d9f6c43#%EF%B8%8F-options to include Sveltestrap by passing the `sveltestrap` option (or selecting it in the interactive menus)

**Comment by babichjacob** [comment]
Any missing imports or other feedback should be posted in https://github.com/svelte-add/svelte-add/issues/31.
Thank you!
