### ISSUE TITLE
Svelte Add on fresh install

### ISSUE THREAD

**Issue by noudard** [svelte-add/svelte-add#161]
Hello,
When il try to add bulma with npx svelte-add@latest bulma on a fresh install and run dev, i got an error :

_rollup v2.59.0
bundles src/main.js → public/build/bundle.js...
[!] Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
src/app.scss (2:0)
1: /* Write your global styles here, in SCSS syntax. Variables and mixins from the src/variables.scss file are available here without importing */ /* Import only what you need from Bulma */
2: @import "bulma/sass/utilities/_all";_
.....

Thanks a lot

**Comment by manuel3108** [comment]
As far as i can see you are trying to use svelte-add on a setup including the rollup bundler.
`svelte-add` only supports vite-powered environments, see here [creating-a-vite-powered-svelte-app-with-integrations](https://github.com/svelte-add/svelte-add#%EF%B8%8F-creating-a-vite-powered-svelte-app-with-integrations)

If this is the case, what you are trying to do is not support.

**Comment by manuel3108** [comment]
As described in the linked readme, please create your application as follows:

```
npm init @svelte-add/vite@latest
```

After that you should be able to add bulma as you are trying to do right now

**Comment by noudard** [comment]
Thanks a lot
