### ISSUE TITLE
Routify

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [svelte-add/svelte-add#165]
What can I do to help add Routify support?

**Comment by babichjacob** [comment]
These questions need to be answered before we can support Routify:
* Is there a Routify template every app is based on?
* Is it created from cloning or using an `npm init`-esque command? 
* Is the initializer simple or stable enough to be wrapped like we're able to do for SvelteKit and Vite? I know about Stackmix which I don't currently fully understand. 

Hopefully these questions are easy to answer, and that Routify 3's support for SvelteKit has made things easier, but I haven't done the research. 

Then, we can go over [the list of integrations supported](https://github.com/svelte-add/svelte-add#-built-in-integration-adders) and reverse engineer Routify templates that have these set up, or implement tutorials for them in code.

**Comment by manuel3108** [comment]
This adder already exists for nearly two years now. Closing.
