### ISSUE TITLE
TailwindCSS: Can't use @apply directive properly with darkmode or hover

### ISSUE THREAD

**Issue by kharann** [svelte-add/svelte-add#169]
Hi! I have some issues with dark mode currently when using the @apply in style.

## Doesn't work

```svelte
<section class="mt-4">
	<h1 class="title">
		Hello World
	</h1>
</section>

<style lang="postcss">
	.title {
		@apply text-primary-2 dark:text-primary-4;
	}
</style>
```

Here's a few examples that work:

## Inline Classes 
```svelte
<section class="mt-4">
	<h1 class="text-primary-2 dark:text-primary-4">
		Hello World
	</h1>
</section>
```

 
## With global in style

```svelte
<section class="mt-4">
	<h1 class="title">
		Hello World
	</h1>
</section>

<style lang="postcss" global>
	:local(.title) {
		@apply text-primary-2 dark:text-primary-4;
	}
</style>
```

## Dark in a parent class in the same file

```svelte
<section class="mt-4 dark">
	<h1 class="title">
		Hello World
	</h1>
</section>

<style lang="postcss">
	.title {
		@apply text-primary-2 dark:text-primary-4;
	}
</style>
```

Overall:
1. Dark mode seems to work, with the correct configuration from tailwind.config.cjs
2. Adding `dark` to the HTML body classes seems to work correctly with inline tailwind styles
3. @apply does not work when the element with the dark class is not in the same file
4. Setting global, and scoping the class to local seems produce expected behavior

### Expected behaviour

The first example should work. I think it's some problems with scoping?

**Comment by babichjacob** [comment]
Thanks for the report! As you've found, there isn't a bug here but you do have to go through extra steps to get it to work the way you expect: you indeed have to go with the third approach you listed ("With global in style"). 

There was discussion about this before here https://github.com/svelte-add/svelte-add/issues/92#issuecomment-774545721

And an explanation for why the workaround works [in the Discord server](https://discord.com/channels/457912077277855764/457912077277855766/822619450686701640):

you wrote
```html
<style lang="postcss" global>
  :local(button) {
    @apply dark:bg-blue-700;
  }
</style>
```
it first turns into
```html
<style global>
  .dark :local(button) {
    --tw-bg-opacity: 1;
    background-color(1,2,3,var(--tw-bg-opacity)); /* whatever the color is */
  }
</style>
```
then into
```html
<style>
  :global(.dark) button {
    --tw-bg-opacity: 1;
    background-color(1,2,3,var(--tw-bg-opacity)); /* whatever the color is */
  }
</style>
```

**Comment by justingolden21** [comment]
So what solution would you guys recommend here?

I would add the dark styles to a custom class and then `@apply` it, but I can't `@apply` a custom class.

I'd inline it, but that means **every single** item in the component needs to have the same classes copied and pasted.

But that seems to be the only working answer is to copy and paste the same classes over and over...
