### ISSUE TITLE
tailwindcss - npm run package does not compile normalize css

### ISSUE THREAD

**Issue by esoteloferry** [svelte-add/svelte-add#180]
Hi all, I am using sveltekit with tailwind to create a package `npm run package` .  The components are styled with tailwind and I can see the final result in dev mode by using the $lib/Components in routes/index.svelte.  

When I need to publish it , first I have to run `npm run package` to compile my component library to package folder.  The styles are compiled BUT the normalize css is not added (@ tailwind base), this means that the published files are different to my dev mode result (inconsistency).   

What is the best approach to add the normalize css  for components library?

For background, this is the component :
https://github.com/mdof/matrix-algebra-svelte/blob/main/src/lib/Input.svelte

Style issue: When focus on any input, there should be a ring indigo but there is nothing.

**Comment by V-Py** [comment]
I'm having the exact same kind of problem, when publishing my package on npm I'm loosing all the style relative to tailwindcss !
I still don't know if it's a configuration problem on my side, but since I found this issue, I took the liberty to share.
If you want more context/see the eventual config issue : https://github.com/V-Py/kanban-svelte

**Comment by esoteloferry** [comment]
> I'm having the exact same kind of problem, when publishing my package on npm I'm loosing all the style relative to tailwindcss ! I still don't know if it's a configuration problem on my side, but since I found this issue, I took the liberty to share. If you want more context/see the eventual config issue : https://github.com/V-Py/kanban-svelte

I had the same issue of loosing ALL the tailwind styles, but got a workaround if you want to try (maybe does not fit , because you use type="text/scss" ): instead of setting the styles in the tag, put them in <style> with @ apply and then use it in your tag. f.e:

`<div class="kanban-container">...`

`<style lang="postcss">
.kanban-container{
@apply flex-1 w-full flex justify-start  [also your background color];
}
</style>`

After running `npm run package` , your components will have the styles but then you will have my issue where the normalize css (used in preflight with @ apply base) is not exported with your component.

**Comment by V-Py** [comment]
Thank you very much for the tip will try this and keep track of your issue in the same time 👍

**Comment by atuttle** [comment]
Just want to chime in as yet another person who would like to use Tailwind to develop a shared component library. I'm not willing to use the `@apply` workaround because of its drawbacks: increased CSS size and complexity of using `@apply` (Adam Wathan has said that if they could go back in time they never would have created `@apply`...)

**Comment by atuttle** [comment]
One of the very helpful people on the Tailwind Discord server (Thanks, @crswll!) helped me find a good(ish) solution to this problem.

If you're building a set of components for other projects to consume, let's say you have your design system, and your consumer project.

In your consumer project, it must use tailwind as you normally would, and then update the `content` setting in your `tailwind.config.cjs` like so:

from: `content: [ './src/**/*.{html,js,svelte,ts}' ]`
to:

```js
content: [
	'./src/**/*.{html,js,svelte,ts}',
	'./node_modules/DESIGN_SYSTEM/**/*.{html,js,svelte,ts}'
]
```

This also works if your design system is in an org, with and without using `npm link` to attach it for local development purposes:

```js
content: [
	'./src/**/*.{html,js,svelte,ts}',
	'./node_modules/@COMPANY/DESIGN_SYSTEM/**/*.{html,js,svelte,ts}'
]
```

This might not be an ideal solution for something like a public-facing project, given the requirement that the consuming project install Tailwind and modify the config, but it's certainly good enough for an internal project for your company.

**Comment by AdrianGonz97** [comment]
The solution above is how most component libraries using tailwindcss solve it. I'm not aware of any that compile the css ahead of time and distribute it as part of the package. I'm also not sure how this relates to the tailwindcss adder. Therefore closing.
