### ISSUE TITLE
Request for flowbite

### ISSUE THREAD

**Issue by shinokada** [svelte-add/svelte-add#182]
I'd like to request to implement `npx svelte-add@latest flowbite`.

[flowbite](https://github.com/themesberg/flowbite)

**Comment by benmccann** [comment]
Seems like all you need to do is install the package and add a tailwind plugin. Is this worthy of an adder?

https://flowbite.com/docs/getting-started/svelte/

**Comment by benmccann** [comment]
Reading through https://github.com/themesberg/flowbite/issues/67 it seems more like you encountered bugs with that library or something along those lines. It doesn't really seem like the setup is complicated. Also Svelte support was added afterwards, so hopefully that works better. I'm going to go ahead and close this then
