### ISSUE TITLE
Unexpected behavior when it comes to the default directory name

### ISSUE THREAD

**Issue by johndeighan** [svelte-add/svelte-add#183]
This is the first I've tried using svelte-add. I used the recommended command:
`npm init @svelte-add/kit@latest
`
The first thing I found was that when prompted for the directory name to create, I got the default `new-svelte-app`, but my backspace key did nothing and I couldn't find a way to change the default name.

**Comment by babichjacob** [comment]
Thanks for your feedback on the project! It's extremely useful to know what people who aren't me think of it. I've split up this issue into multiple ones and addressed all of them except #187 and #188, which I still need to look at.
