### ISSUE TITLE
Getting this weird error in vscode when I use style lang="scss"

### ISSUE THREAD

**Issue by Cajaye** [svelte-add/svelte-add#184]
Everything works perfectly but the error message is annoying
![2022-01-28](https://user-images.githubusercontent.com/86979554/151643916-8ab686f9-094d-4855-b63c-52705c3eec43.png)

**Comment by babichjacob** [comment]
I saw someone post this solution on Discord: https://discord.com/channels/457912077277855764/689494103380983930/961637486168244294

We might be able to update `svelte-add` to work this way.

**Comment by manuel3108** [comment]
It looks like this is not happending anymore
