### ISSUE TITLE
Sass (not SCSS)

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/svelte-add#187]
originally posted in #183:

I'd really like to see an adder for SASS, especially with the original, indentation-based syntax. I use CoffeeScript because it uses indentation-based syntax and I'd like to use the same kind of syntax in my CSS.

**Comment by ThatXliner** [comment]
Shouldn't adding `sass` to package.json and leaving `sveltePreprocess()` unconfigured work as well? Also, where docs for making a new adder?

**Comment by babichjacob** [comment]
> Shouldn't adding `sass` to package.json and leaving `sveltePreprocess()` unconfigured work as well? 

A user who wants to manually set things up can do this about that easily, yeah! `svelte-add`, which is interested in making things work in a wide variety of situations, hasn't implemented this adder yet because of the difficulty that is converting an existing CSS syntax file into Sass. I haven't looked into packages for this yet.

> Also, where docs for making a new adder?

I haven't written any and I don't really plan on it until after all the adders listed in the main README have been rewritten to be built-in to `svelte-add`. I just suggest reaching out to me in the [issue for the relevant adder](https://github.com/svelte-add/svelte-add/labels/make%20a%20new%20adder) or [on Discord](https://discord.com/channels/457912077277855764/948044367568994355/948085841253769216) to talk about things. 

Like I wrote there, adders can vary quite a bit in what they do, so the tools `svelte-add` provides vary in usefulness for them. For that reason, you have to know what the integrations you have in mind are to reference the most similar adder (hopefully there is one) or ask for help with it.

**Comment by manuel3108** [comment]
This is done, see #303
