### ISSUE TITLE
Update mdsvex to use `defineMDSveXConfig`

### ISSUE THREAD

**Issue by PuruVJ** [svelte-add/svelte-add#189]
In 0.10.2 of `mdsvex`, a new TS helper `defineMDSveXConfig` was released, which provides great TS support. I recommend updating mdsvex template to make use of it

```ts
import { defineMDSveXConfig } from 'mdsvex';

export default defineMDSveXConfig({
  /**/
})
```

**Comment by babichjacob** [comment]
Closed by https://github.com/svelte-add/mdsvex/commit/0eed6dbb98f2afc871408bac375d151570804d35 / https://github.com/svelte-add/svelte-add/commit/898da718c5d00cb639bbf41a228535a62c82d7f2. Thank you!

**Comment by PuruVJ** [comment]
Thanks for this!
