### ISSUE TITLE
Svelte-add Tailwind CSS comes after svelte:head

### ISSUE THREAD

**Issue by shinokada** [svelte-add/svelte-add#190]
I add a css file in the `svelte:head` section. I'd like to have it after Svelte-add Tailwind CSS, but it is placed before it.

How to place additional CSS after Svelte-add Tailwind CSS?

![image](https://user-images.githubusercontent.com/147320/151883142-50a38182-7cea-46f7-94fc-113d9c1ff89c.png)

**Comment by babichjacob** [comment]
All your global styles should be in `src/app.css` so you can decide what order they should be in. 

Specifically as it concerns Flowbite, follow their [guide to install it as a Tailwind plugin](https://flowbite.com/docs/getting-started/quickstart/) rather than using their unpurged CDN CSS.

**Comment by shinokada** [comment]
@babichjacob Thank you for your reply. I have tried it before and it doesn't work.
Only way it works is using the external CDN.

As you see in [this discussion](https://github.com/themesberg/flowbite/issues/51), it is not only for Svelte.
I posted [my problem](https://github.com/themesberg/flowbite/issues/67) as well.

If it works for you, I will be happy to see how you did it.

**Comment by shinokada** [comment]
I removed the CDN CSS and added in the `__layout.svelte` and it works. 
Thanks.

```
<script>
  import "../app.css";
  import "@themesberg/flowbite/dist/flowbite.css";
</script>

<div class="mx-auto p-2">
  <slot />
</div>
```
