### ISSUE TITLE
Rewrite Vitest adder built-in to `svelte-add`

### ISSUE THREAD

**Issue by rgossiaux** [svelte-add/svelte-add#191]
Would be nice if there was a vitest integration. I tried setting vitest up myself and couldn't get the config working properly, so I'm sure it'd save folks a lot of time if they wanted to try using vitest.

**Comment by davipon** [comment]
I've recently tackled some problems when testing different svelte packages in Vitest: [janosh/svelte-multiselect#48](https://github.com/janosh/svelte-multiselect/issues/48#issuecomment-1054797874).
My DX improves a ton after I switched from Jest to Vitest, so I'm considering writing an adder for that.
Here is an [example](https://stackblitz.com/fork/github/davipon/test-svelte-multiselect?initialPath=__vitest__) you can try online.

**Comment by david-plugge** [comment]
didnt see this issue, oops
#212

**Comment by babichjacob** [comment]
@davipon has created an external adder! Check it out. Renaming this issue accordingly.

**Comment by davipon** [comment]
@benmccann had created a discussion here: https://github.com/sveltejs/kit/discussions/5285
To make Vitest an option in `create-svelte`.

**Comment by manuel3108** [comment]
`create-svelte` is not handled by `svelte-add`, because it's an official package from the core svelte team. Adiitionally this is currently supported by the main `create-svelte` cli
