### ISSUE TITLE
Do you no longer need `cssnano` with `tailwindcss`?

### ISSUE THREAD

**Issue by oekazuma** [svelte-add/svelte-add#194]
I installed `tailwindcss` in a new SvelteKit project using `svelte-add`, but `cssnano` was not installed. 
Is `cssnano` no longer needed?

Commands used
```
npm init svelte@next my-app

npx svelte-add@latest tailwindcss
```

postcss.config.js
```js
const tailwindcss = require('tailwindcss');
const autoprefixer = require('autoprefixer');

const config = {
	plugins: [
		//Some plugins, like tailwindcss/nesting, need to run before Tailwind,
		tailwindcss(),
		//But others, like autoprefixer, need to run after,
		autoprefixer
	]
};

module.exports = config;
```

package.json
```json
{
	"name": "my-app",
	"version": "0.0.1",
	"scripts": {
		"dev": "svelte-kit dev",
		"build": "svelte-kit build",
		"package": "svelte-kit package",
		"preview": "svelte-kit preview",
		"check": "svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --ignore-path .gitignore --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
		"format": "prettier --ignore-path .gitignore --write --plugin-search-dir=. ."
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"@typescript-eslint/eslint-plugin": "^5.10.1",
		"@typescript-eslint/parser": "^5.10.1",
		"eslint": "^7.32.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^3.2.1",
		"prettier": "^2.5.1",
		"prettier-plugin-svelte": "^2.5.0",
		"svelte": "^3.44.0",
		"svelte-check": "^2.2.6",
		"svelte-preprocess": "^4.10.1",
		"tslib": "^2.3.1",
		"typescript": "~4.5.4",
		"postcss": "^8.4.5",
		"postcss-load-config": "^3.1.1",
		"autoprefixer": "^10.4.2",
		"tailwindcss": "^3.0.12"
	},
	"type": "module"
}
```

**Comment by vhscom** [comment]
I think you'd only want to minify CSS in production builds. And given environment-specific settings may be project specific perhaps it best left to end-users? For those looking, here's [one way to add it](https://github.com/vhscom/svelte-headlessui-starter/commit/c4a7aaab5e21fc81c122c516df18a7d9390e4b23#diff-8359bb716171c7a71348ef352134d5f6dcad444956e4e0362e5e61e6856edeca). Personally I'd like to see this somehow worked into `svelte.config` inside SvelteKit for centralized config management.

**Comment by oekazuma** [comment]
I agree with the idea of leaving it up to the end user.
Recently I learned that there is another minifier besides `cssnano` called `parcel-css`.
Thanks! I will close this.

As a side note, `parcel-css` is said to have better performance and smaller size than `cssnano`.

[Benchmarks](https://github.com/parcel-bundler/parcel-css#benchmarks)
