### ISSUE TITLE
`__layout.svelte` in a generated app with tailwindcss and example code uses incorrect header

### ISSUE THREAD

**Issue by avarun42** [svelte-add/svelte-add#195]
If you generate an app with tailwindcss and typescript and tailwind forms and tailwind typography, and choose "yes" to the "generate example code", the generated `__layout.svelte` does not correctly use the `Header` component. It imports `Header` properly, but it uses a standard html `<header />` tag instead of the `<Header />` tag it should be using.

**Comment by codygriffith** [comment]
Thanks, was just having the same issue.

**Comment by bato3** [comment]
Also in scss adder.

Fresh kit demo (ts) + `npx svelte-add@latest scss`

**Comment by babichjacob** [comment]
Thanks for the report! This is a shame because we [just refactored the HTML parser](https://github.com/svelte-add/svelte-add/commit/f29c47d991cc8f115514d33d9d75b56ac22eed6c) and I hope this can be overcome — I'll look into it later on.

**Comment by manuel3108** [comment]
This is solved with the latest update.
