### ISSUE TITLE
deploy svelte md app on heroku

### ISSUE THREAD

**Issue by ElectriCherph** [svelte-add/svelte-add#196]

**Comment by babichjacob** [comment]
I don't use Heroku so I don't personally know. It's also likely to be dependent on whether you use SvelteKit or non-Kit Vite-powered Svelte, and dependent on if you build SvelteKit to a static app or one with a running server.

Try reaching out on [the Svelte Discord server](https://svelte.dev/chat) with more information for help.

**Comment by babichjacob** [comment]
Closing due to age, and that the previous answer contains everything I know.
