### ISSUE TITLE
Svelte Add Tailwind CSS (using TypeScript)?

### ISSUE THREAD

**Issue by vhscom** [svelte-add/svelte-add#197]
I saw there's a way to use PostCSS with a TypeScript config (It's supported by the loader) but I haven't gotten it working with SvelteKit yet. Has anyone figured out a clean way to do this, even if it requires some updates to Svelte Config? Perhaps your changes could be worked into the Adder to help us work away from `require` statements and CJS syntaxes.

**Comment by vhscom** [comment]
Potentially related: https://github.com/vitejs/vite/issues/5316

**Comment by yorickshan** [comment]
same issue

**Comment by manuel3108** [comment]
This seems to be currently working
