### ISSUE TITLE
Feature Request — Obfuscate Tailwind CSS classes

### ISSUE THREAD

**Issue by hmaesta** [svelte-add/svelte-add#198]
For performance proposes, everything that can be made to improve final bundle size is welcome. Even better if **automated.**

As feature request, would be nice to obfuscate classes on production bundle. Like [webpack-obfuscator](https://github.com/javascript-obfuscator/webpack-obfuscator), for example.

## Example

Original code:

```
# index.vue
<div class="text-gray-500">Hey!</div>

# tailwind.css
.text-gray-500 { color: #888; }
```

Final code:
```
# index.html
<div class="a">Hey!</div>

# tailwind.css
.a { color: #888; }
```

**Comment by babichjacob** [comment]
What libraries can achieve this? This would be a good option if we could add it as a plugin to the PostCSS config.

**Comment by hmaesta** [comment]
I honestly never had success accomplishing this, even with Webpack. For standalone Vite (or PostCSS) I can't even find a reference.

If it helps, some readings:

- React with css-modules: [(1)](https://develoger.com/how-to-obfuscate-css-class-names-with-react-and-webpack-20e2b5c49cda) [(2)](https://shouvikbhuiyan.medium.com/obfuscate-css-classname-in-a-react-app-scaffolded-using-create-react-app-70da56b18535)
- Vue with css-modules: [(1)](https://dev.to/radonirinamaminiaina/let-obfuscate-it-optmisation-technic-gd1) [(2)](https://vue-loader.vuejs.org/guide/css-modules.html#usage) 
- [mangle-css-class-webpack-plugin](https://github.com/sndyuk/mangle-css-class-webpack-plugin)

**Comment by manuel3108** [comment]
This doesn't look like this is a mainstream issue and should therefore be handled individually.
