### ISSUE TITLE
Gracefully handle failure situations.

### ISSUE THREAD

**Issue by Leftium** [svelte-add/svelte-add#20]
Currently, the adders just blindly try their actions, and always report as if they were successful.
- The adders should check if the actions can be completed and/or confirm the actions were completed.
- Then show warning/error messages as appropriate.
- It would also be good to stop execution of an adder if there is something wrong.
- And maybe roll back any changes on failure.

Two specific examples of where this would help:
- I accidentally ran svelte-add in the parent directory, creating a postcss.config.cjs file there. Later, this file caused problems in a fresh project created with `npm init svelte@next child-directory`
- I ran svelte-add postcss. It was not successful, but it looked like it worked according to the CLI output. So it was confusing when postcss wasn't working in my SvelteKit project.

**Comment by babichjacob** [comment]
This should be fixed by 1fe58221bc2133c57e4ebf6f302b314d97a0a4d3. Leaving this issue open for bug reports though.

**Comment by babichjacob** [comment]
Closing this so that new issues can be made for specific situations where this doesn't work.
