### ISSUE TITLE
Add daisyUI option to TailwindCSS

### ISSUE THREAD

**Issue by vhscom** [svelte-add/svelte-add#200]
In addition to `forms` and `typography`, I'd like a `daisyui` option as well. https://daisyui.com/

**Comment by babichjacob** [comment]
Just implemented this and published it to npm. Check it out:
```sh
pnpm create @svelte-add/kit@latest my-new-app --with tailwindcss --tailwindcss-daisyui
```

**Comment by vhscom** [comment]
That's awesome. I tried it and it works perfectly. I dropped a new issue #207 and I wasn't able to figure out how to do the above command and achieve TypeScript, Prettier and ESLint. I think I was almost there. But I couldn't quite figure it out.

**Comment by vhscom** [comment]
> Just implemented this and published it to npm.

That's awesome. I tried it and it works perfectly. I dropped a new issue #207 as I wasn't able to figure out how to do the above command and achieve TypeScript, Prettier and ESLint. I think I was almost there. But I couldn't quite figure it out.

Thank you for your continued work on this awesome project.
