### ISSUE TITLE
Gitpod file and HMR intergration

### ISSUE THREAD

**Issue by LeoDog896** [svelte-add/svelte-add#202]
Gitpod and sveltekit do _not_ mix together -- luckily, gitpod has an integration guide for HMR. I think this would work great as a svelte-adder. 

Link: https://github.com/gitpod-io/template-sveltekit/

**Comment by AdrianGonz97** [comment]
Based on the linked template, it looks like the only thing that needs to be added for it to work is the [`.gitpod.yml` file](https://github.com/gitpod-samples/template-sveltekit/blob/main/.gitpod.yml). I don't think this amount of work justifies the need to be an official adder
