### ISSUE TITLE
Github Actions adder

### ISSUE THREAD

**Issue by LeoDog896** [svelte-add/svelte-add#203]
An adder for github actions -- just a new file on ./github/workflows/publish.yml: 

I have an example here: https://github.com/LeoDog896/scannable/blob/master/.github/workflows/publish.yml, but that's for a subdirectory (/demo in that case). Something like that, as well as a paramater for the repository name (if possible, grab that from git) to check if the base directory should be somewhere else (in the svelte config file, `config.paths.base`)

**Comment by babichjacob** [comment]
Setting up GitHub Actions would be an option for each adder since how it's expected to work depends on the deployment target.

**Comment by babichjacob** [comment]
(When we have other deployment adders, I'll apply their labels to this issue)

**Comment by LeoDog896** [comment]
In that case, I think a GitHub actions option for each deployment + a standalone GitHub action for vanilla setups would be nice -- ill create an external adder.

**Comment by LeoDog896** [comment]
Going to be fully honest the documentation for external adders is *very* confusing -- in that case, would it be possible for there to be a standalone Github Action for static sites, as well as sometime in the future options for github actions for other types of deployments?

**Comment by manuel3108** [comment]
Duplicate of #339
