### ISSUE TITLE
app.scss is not included

### ISSUE THREAD

**Issue by MarcSallent** [svelte-add/svelte-add#205]
Hello

Using sveltekit with the SCSS adder. Of all the methods specified in "Using SCSS" in the readme file, the following work:

> - You can write SCSS syntax in the style lang="scss" blocks in Svelte files.
> - You can write SCSS syntax in the src/variables.scss file.

But not this one. Nothing that I add in this file has any effect on the application
> - You can write SCSS syntax in the src/app.scss file.

Thanks

**Comment by babichjacob** [comment]
Did you have an existing project you added SCSS to, or did you use the app initializer to start a new project with SCSS?

If you started a new project, (which by the way I did locally with `pnpm create @svelte-add/kit -- --with scss testing-new-scss` to reproduce this problem), it worked just fine for me. I tested by writing `body { background-color: $primary }` in `src/app.css` and `$primary: green;` in `src/variables.scss`.

If you added it to an existing project, do you have a repository showing this? Preferably a commit right before running the command and one right after running it similarly to [how it's described in the README](https://github.com/svelte-add/svelte-add#-safely-adding-integrations-and-examining-changes).

**Comment by SimpleProgrammingAU** [comment]
I have run into the same problem. Assuming @MarcSallent did the same thing as me, I created the project using `npm create svelte@latest my-app` rather than `npm create svelte-add/kit...`.

Should `svelte-add` work with fresh projects made with `npm create svelte`?
