### ISSUE TITLE
Commands for common setups

### ISSUE THREAD

**Issue by vhscom** [svelte-add/svelte-add#207]
Given the great degree of customization svelte-add provides I find myself struggling to do basic stuff now. For example, I want to create a new SvelteKit project using `pnpm create` with DaisyUI and I keep hitting errors. I have reviewed the docs several times though it's not clear what I'm doing wrong:

Here are some of the ways I've tried:
```
pnpm create @svelte-add/kit@latest flowerpatch --with prettier+eslint+typescript --with tailwindcss --forms --typography --tailwindcss-daisyui
pnpm create @svelte-add/kit@latest flowerpatch -- --with prettier+eslint+typescript -- --with tailwindcss --forms --typography --tailwindcss-daisyui
pnpm create @svelte-add/kit@latest flowerpatch --with prettier+eslint+typescript+tailwindcss --forms --typography --tailwindcss-daisyui
```

Here was the one I initially expected to work before revisiting the docs:

```term
pnpm create @svelte-add/kit@latest flowerpatch -- \
  --with tailwindcss --forms --typography --tailwindcss-daisyui \
  --with typescript prettier eslint \
```

Perhaps it would be helpful if there were a doc with some commonly used recipes, or a discussion section with recipes representing favorite setups and the commands needed to create them. Or just a few more examples in the README.

The problem with recipes is they will go out of date as soon as the API changes so maybe that's not such a good idea after all. In the past I've typically resorted to using NPM and running adders one at a time.

**Comment by manuel3108** [comment]
Relates to #269
