### ISSUE TITLE
🚀⚡️🎨🧹📄 Emoji commit messages ⁉️

### ISSUE THREAD

**Issue by oneezy** [svelte-add/svelte-add#208]
I apologize for asking this here so please feel free to `close` or `delete` after, but what tool(s) are being used to create the **emoji commit messages**? 

We recently began using [PNPM Workspaces](https://pnpm.io/workspaces) + [Turborepo](https://turborepo.org/) and have been looking for an elegant solution like this.

![image](https://user-images.githubusercontent.com/7369575/170181183-53504380-b9a9-446b-a5d7-11b84416fed3.png)

**Comment by babichjacob** [comment]
No need to apologize! I just type those manually with every commit — using the emoji picker built in to macOS (Ctrl+Command+Space) or Windows (Windows key + .) depending on which I'm using at the time.

So it's completely open to being messed up or forgotten. Here's the list I've been using (sorted by usefulness):
```
🐛 fix
⚡️ feat
📄 docs
🚀 meta
🎨 style
🏎 performance
🦠 vulnerability
🌊 upstream
```

**Comment by babichjacob** [comment]
Only closed for issue tracking purposes — feel free to ask or talk more :)

**Comment by oneezy** [comment]
thanks!
