### ISSUE TITLE
Running npm init @svelte-add/kit@latest creates a wrong app.html file.

### ISSUE THREAD

**Issue by myz-dev** [svelte-add/svelte-add#210]
Hello everyone,
I assume this is a bug, I am not sure:
Running `$ npm init @svelte-add/kit@latest` should create a new ready-to-go sveltekit project right?
For me this created the project with a wrong `app.html` file. Running `npm run dev -- --open ` leads to an error page that describes the solution already:

> Error: %svelte.assets% in src/app.html should be replaced with %sveltekit.assets%
    at load_template (file:///../node_modules/@sveltejs/kit/dist/cli.js:693:10)
    at file:///../node_modules/@sveltejs/kit/dist/chunks/plugin.js:357:24

(I omitted the absolute paths here)

The created file looks like this:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="description" content="" />
		<link rel="icon" href="%svelte.assets%/favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		%svelte.head%
	</head>
	<body>
		<div>%svelte.body%</div>
	</body>
</html>

```
Instead I believe it should create this:
 ```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="description" content="" />
		<link rel="icon" href="%sveltekit.assets%/favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		%sveltekit.head%
	</head>
	<body>
		<div>%sveltekit.body%</div>
	</body>
</html>
```

Also running the command I get some kind of strange typescript error: This is the complete output:

> npm init @svelte-add/kit@latest
➕ Svelte Add's SvelteKit app initializer (Version 2022.05.24.01)
✔ What directory should your app be created in? … web
✔ What scripting language will you write your app in? › TypeScript
✔ What language will you write your app styles in? › PostCSS (used by Tailwind CSS)
✔ Do you want to use Autoprefixer?
https://github.com/postcss/autoprefixer
 › No
✔ What framework will you use for your app's styles? › Tailwind CSS
✔ Do you want to use the Tailwind CSS Forms plugin?
https://github.com/tailwindlabs/tailwindcss-forms
 › Yes
✔ Do you want to use the Tailwind CSS Typography plugin?
https://github.com/tailwindlabs/tailwindcss-typography
 › Yes
✔ Do you want to use daisyUI?
It provides component classes for Tailwind CSS. https://daisyui.com/
 › No
✔ What other features do you want for your app? › 
✔ What code quality tools do you want to help maintain your app? › ESLint, Prettier
✔ Where will you deploy your app? › Nowhere (set up a deployment target later)
✔ Do you want example code added to your app to demonstrate how to use the tools you've selected? › No. Keep it completely minimal.
✔ Should your app's dependencies be installed with npm right now? › Yes

TypeScript
  ❌ `typescript` is installed
  ❌ `tsconfig.json` exists

  ❌ was supposed to be set up for you but it appears not to have been?! (see above)
This is definitely not supposed to happen, so please create or find an existing issue at https://github.com/svelte-add/svelte-add/issues with the full command output.
🪄 Your PostCSS + Tailwind CSS + ESLint + Prettier SvelteKit app is ready!
❌ Could not identify correct installation of TypeScript. 
This is definitely not supposed to happen, so please create or find an existing issue at https://github.com/svelte-add/svelte-add/issues with the full command output.
  1. cd web
  2. npm run dev -- --open  # start developing with a browser open

I definitively have typescript installed as a global package. Running `tsc --version` yields `Version 4.7.4`.
Are these issues connected?
Best regards

**Comment by babichjacob** [comment]
> Are these issues connected?

Yes, the issue is that `npm` for some reason installed an old version of `create-svelte` (which is the package that gets run if you use `npm init svelte`), which both produces an old output and has an old function signature which was changed to allow people to choose type-checked JavaScript. So you get both issues seen here.

What is your system information, like your versions of Node and npm and what operating system you're on? If it's Windows, are you using WSL? Did you install Node in WSL or install Node in Windows and run it through WSL?

**Comment by myz-dev** [comment]
Hi. Sorry for not including any information in the first post, I do not know where my head before...
I am running Windows 10 WSL2, Ubuntu 20.04.
Npm and Npx version: 8.5
Node: v16.14.2
When I can do something to narrow this down further I would be glad to provide more information.

**Comment by manuel3108** [comment]
This does not seem to be happening anymore.
