### ISSUE TITLE
Vitest adder

### ISSUE THREAD

**Issue by david-plugge** [svelte-add/svelte-add#212]
An adder for testing sveltekit with [vitest](https://vitest.dev/).

### things to add

`jsdom` can be replaced by some [other options](https://vitest.dev/config/#environment)

_package.json_
```json
{
	"scripts": {
		"test": "vitest",
		"coverage": "vitest run --coverage"
	},
	"devDependencies": {
		"vitest:": "^0.16.0",
		"vitest-svelte-kit": "^0.0.6",
		"@testing-library/svelte": "^3.1.3",
        "jsdom": "^20.0.0"
	}
}
```
_svelte.config.js_
```js
const config = {
	kit: {
		vite: {
			test: {
				environment: "jsdom"
			}
		}
	}
}
```

_vitest.config.js_
```js
import { extractFromSvelteConfig } from 'vitest-svelte-kit';
export default extractFromSvelteConfig();
```

### jest like globals (optional)

https://vitest.dev/config/#globals

_tsconfig.json_
```json
{
	"compilerOptions": {
		"types": ["vitest/globals"]
	}
}
```
_svelte.config.js_
```js
vite: {
	test: {
		globals: true
	}
}
```

### in-source testing (optional)

https://vitest.dev/guide/in-source.html

_svelte.config.js_
```js
vite: {
	test: {
		includeSource: ['src/**/*.{js,ts,svelte}'],
	}
}
```

**Comment by davipon** [comment]
I think I would write one in the near future.

Few things to note:
- I still have some problems using `happy-dom` especially in component test, `jsdom` seems to be a better choice.
- The adder would need to support both `Svelte` (using `rollup` or `vite`) and `SvelteKit` projects.
- `deps: { inline: [/svelte-component/] }` is unavoidable at this moment (ref: https://github.com/janosh/svelte-multiselect/issues/48)
- `msw` can be a great option to stop mocking `fetch` or `axios`

I'd update here once it's ready.

**Comment by davipon** [comment]
Here is the adder: [svelte-add-vitest](https://github.com/davipon/svelte-add-vitest), please give it a try.

I'll open a PR tomorrow to add the adder to the external integration adders.

**Comment by david-plugge** [comment]
> Here is the adder: [svelte-add-vitest](https://github.com/davipon/svelte-add-vitest), please give it a try.

Pretty nice!

**Comment by david-plugge** [comment]
vs code gives me a type error in svelte.config.js at `kit.vite.test.coverage.exclude`
```
(property) C8Options.exclude?: string[] | undefined
Type 'string' is not assignable to type 'string[]'.ts(2322)
```

**Comment by davipon** [comment]
@david-plugge, somehow my vs code didn't shout at me 😅.

Just fixed it, please give it a try, thx.

**Comment by babichjacob** [comment]
Closing this issue to keep discussion in #191
