### ISSUE TITLE
Show what non-interactive command is equivalent to the prompts the user chose

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/svelte-add#216]
This means at the end of the initialization process that it should say
```sh
pnpm create @svelte-add/kit@latest chosen-destination -- --with typescript+postcss+tailwindcss+playwright --postcss-autoprefixer false --tailwindcss-forms true --tailwindcss-typography false --tailwindcss-daisyui false --package-manager pnpm --demos false --install true
```

in the expanded form and

```sh
pnpm create @svelte-add/kit@latest chosen-destination -- --with typescript+tailwindcss+playwright --postcss-autoprefixer false --tailwindcss-forms true
```
in the compact form (that is to say, when what's chosen aligns with the default).

This would be a very helpful alternative to (but we would still definitely do) https://github.com/svelte-add/svelte-add/issues/207 and https://github.com/svelte-add/svelte-add/issues/147

**Comment by manuel3108** [comment]
Relates to #269

**Comment by manuel3108** [comment]
This is supported by `svelte-add`s successor [`svelte-compose`](https://svelte-compose.com/)
