### ISSUE TITLE
[sveltekit] [vite.config.js] `updateViteConfig` puts config in the wrong file (since latest sveltekit update)

### ISSUE THREAD

**Issue by c00** [svelte-add/svelte-add#219]
Since the latest update, sveltekit no longer uses `svelte.config.js` to store `vite` configuration. Instead the separate `vite.config.js` is used. The function `updateViteConfig` does not seem to reflect this yet, causing the vite config to be placed in the wrong file.

## To reproduce

```bash
npm create svelte svelte-add-scss
cd svelte-add-scss
npm i
npx svelte-add@latest scss
npm i
npm run dev
```

## Result

Notice that the `run dev` command will produce an error: 
```
error when starting dev server:
Error: config.kit.vite has been removed — use vite.config.js instead
```

This error is because `svelte-add` has added the `kit` key and the css config in the file `svelte.config.js`. 
![image](https://user-images.githubusercontent.com/6259056/177750824-122b8fe3-1922-48ad-b506-2d470fcbf622.png)

## Expected

The configuration should have been added to the `vite.config.js` file instead:
![image](https://user-images.githubusercontent.com/6259056/177751032-f3b57aba-5eb6-4057-b27f-91a7f0b40ccc.png)

When making this adjustment manually, `npm run dev` runs without issues.

**Comment by babichjacob** [comment]
Thank you so much for the detailed report! This is highly likely to have been fixed in the most recently published version of `svelte-add` and its related packages (specifically because of commit 602e1b3e41848e0494e2fc36ac1c1091d7b18d40)

**Comment by babichjacob** [comment]
For organizational purposes: this was the same issue as #217
