### ISSUE TITLE
Add Electron

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/svelte-add#22]
Notes:
* https://github.com/FractalHQ/sveltekit-electron
  * I forgot if I was given permission to rip this off or not
* https://github.com/Dax89/electron-sveltekit
* https://mobile.twitter.com/el3um4s/status/1416423321449676804
  * https://github.com/el3um4s/memento-sveltekit-electron-typescript
* https://github.com/malynium/electrekit
* https://github.com/Blade67/Sveltron
* https://github.com/KraXen72/svelte-electron-quick-start
* https://github.com/cawa-93/vite-electron-builder
* https://fireship.io/snippets/svelte-electron-setup/
* https://github.com/d-subrahmanyam/svelte-electron-ts-todo-app
* https://github.com/ptkdev-boilerplate/svelte-electron-boilerplate

**Comment by ThatXliner** [comment]
I like https://github.com/cawa-93/vite-electron-builder
