### ISSUE TITLE
@svelte-add/tailwindcss Replace "prettier-plugin-svelte" with  "prettier-plugin-tailwindcss"

### ISSUE THREAD

**Issue by 123remodeling** [svelte-add/svelte-add#229]
When `npx svelte-add@latest tailwindcss` is used, it should replace [@sveltejs/prettier-plugin-svelte](https://github.com/sveltejs/prettier-plugin-svelte) with [@tailwindlabs/prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) in the `package.json` since it includues both TailwindCSS and Svelte formatters.

**Comment by manuel3108** [comment]
@123remodeling Thanks for raising the issue. @alongcamewayne was kind enough to implement this feature. 

This feature is available with the latest release of svelte-add.

Thanks to everyone involved!
