### ISSUE TITLE
svelte-add broken since SvelteKit update? Can't install dependencies (anymore) 

### ISSUE THREAD

**Issue by SMEETT** [svelte-add/svelte-add#235]
### **What's the issue?**
When trying to install dependencies I get the error shown below. Forcing the installation of dependencies (using `--legacy-peer-deps`) works, but then the build-process fails.

###  **How to reproduce:**
`npm create @svelte-add/kit@latest test_proj`

### **Platform:**
**OS:** Win 11 Enterprise / 21H2 / Build: 22000.856
**Node:** 16.17.0
**NPM:** 8.15.0
**Build-Adapter:** adapter-node

### **Error-Message**
![ebfBb8d](https://user-images.githubusercontent.com/62242334/187551156-8c7e2bd7-60cf-4b2d-b060-764574b51ffd.png)

### **`npm install --legacy-peer-deps && npm run build` leads to:**

![puc](https://user-images.githubusercontent.com/62242334/187552301-0d23255e-107f-4f66-a0d2-2196b971bf4a.png)

Interestingly enough the local dev-server seems to work just fine after forcing the installation of dependencies.

Finally I tried building the current version of SvelteKit without issues. Only thing I noticed when installing `adapter-node`
I get warnings that seem related:

![pic](https://user-images.githubusercontent.com/62242334/187554299-d60a0837-ace7-4d9f-93bb-1a741cad9d38.png)

Anyone else has seen something similar? I am bit surprised I can't find anything.

Thanks for reading everyone o/

**Comment by SMEETT** [comment]
SOLUTION for now (thanks to @danawoodman from the official Svelte Discord-Server):
1. `npm create svelte` 
2. `npx svelte-add@latest [options]`

Using `svelte-add` alone seems to fail at the moment, but when we use it to actually **add** to an already existing SvelteKit project it works.

**Comment by charbelnicolas** [comment]
These breaking changes are making a mess all over the place....

**Comment by babichjacob** [comment]
Thanks for the report. I'm sorry this happened!

It looks like Svelte Add's SvelteKit app initializer tried to run `npm install` for you after it had already successfully created the project, but because SvelteKit has a dependency on a beta release of Vite, it failed. 

The project would already be created at this point, so you could intervene and install packages manually. To prevent the app initializer from attempting to install packages for you, you can [pass `--install false` as an option](https://github.com/svelte-add/svelte-add#%EF%B8%8F-options).

We can update Svelte Add so that package installation failure isn't displayed as a total failure.

**Comment by renefournier** [comment]
> Thanks for the report. I'm sorry this happened!
> 
> It looks like Svelte Add's SvelteKit app initializer tried to run `npm install` for you after it had already successfully created the project, but because SvelteKit has a dependency on a beta release of Vite, it failed.
> 
> The project would already be created at this point, so you could intervene and install packages manually. To prevent the app initializer from attempting to install packages for you, you can [pass `--install false` as an option](https://github.com/svelte-add/svelte-add#%EF%B8%8F-options).
> 
> Fortunately, Vite 3.1.0 has been released so a beta version of Vite isn't needed anymore, so this issue was fixed upstream!
> 
> We can update Svelte Add so that package installation failure isn't displayed as a total failure.

Hi @babichjacob I now realize this is breaking my Kit app. Are you going going to update `svelte-add`? Or what would you suggest I do to add **bulma** with sass? TY!

**Comment by manuel3108** [comment]
As far as I understand, the comment's here svelte-add is failing because it failed to install the dependencies. But you should be able to install them manually. 
I know it has been a long time, but can you explained in more details what broke?
