### ISSUE TITLE
Support for executing svelte-add with options enabled

### ISSUE THREAD

**Issue by chikaj** [svelte-add/svelte-add#238]
Can you provide examples of how to use svelte-add with options?

If an option is false by default, how do I enable it?

![image](https://user-images.githubusercontent.com/10135346/188922036-fe8497ec-473f-42c8-a208-c65b1fd7fbf8.png)

**Comment by babichjacob** [comment]
This is a great idea! It just hasn't been gotten around to yet.

If you want to use an option on the command line, you can enable it with `--option-name true`. I believe you can also write just `--option-name`:

```sh
npx svelte-add@latest tailwindcss --forms true
npx svelte-add@latest tailwindcss --forms 

# Multiple
npx svelte-add@latest tailwindcss --forms true --daisyui true
npx svelte-add@latest tailwindcss --forms --daisyui
```

I don't believe you have to escape the options from `npx`, but if you do, you'd have to write those commands above like these:

```sh
npx svelte-add@latest tailwindcss -- --forms true
npx svelte-add@latest tailwindcss -- --forms 

# Multiple
npx svelte-add@latest tailwindcss -- --forms true --daisyui true
npx svelte-add@latest tailwindcss -- --forms --daisyui
```



Will close to keep discussion in https://github.com/svelte-add/svelte-add/issues/207 - subscribe to that issue for updates.
