### ISSUE TITLE
Use `vitePreprocess` rather than `svelte-preprocess`

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#244]
If you setup a new TypeScript project with `npm create svelte@latest` it will now use `vitePreprocess`. If you then run `pnpx svelte-add@latest tailwindcss` you end up with both preprocessors configured in the `svelte.config.js`

**Comment by oneezy** [comment]
can confirm

**Comment by braden-w** [comment]
Can confirm, and for those who have errors, the Tailwind CSS docs have updated [the guide for installing TailwindCSS for Sveltekit](https://tailwindcss.com/docs/guides/sveltekit) with the following for vitePreprocess()

```ts
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter()
  },
  preprocess: vitePreprocess()
};

export default config;
```

rather than `svelte-prerocess`.

**Comment by manuel3108** [comment]
I have just released a version which fixes this behavior.

I would be happy if some of you could test some of the adders, to confirm that this change is working as expected. Especially the `scss` and `postcss` adders would be important, as they are the main adders that are affected by this.

**Comment by rudiv** [comment]
This confused me for a little, with a brand new (fully up to date) svelte-kit app, after running `npx svelte-add@latest tailwindcss` an error is emitted when trying to run the dev server:

```
error when starting dev server:
SyntaxError: Identifier 'vitePreprocess' has already been declared
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
    at async link (node:internal/modules/esm/module_job:68:21)
```

As per this issue this is due to the duplicated `vitePreprocess` in the `svelte.config.js`:
```
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";
import adapter from "@sveltejs/adapter-auto";
import { vitePreprocess } from "@sveltejs/kit/vite";
```

Can also confirm that this is present when using `npm create @svelte-add/kit@latest` and adding the tailwind integration.

**Comment by manuel3108** [comment]
Thanks for bringing this to my attention and helping me out in the details @rudiv .

From now on sveltekit projects will use an import like the following:
`import { vitePreprocess } from '@sveltejs/kit/vite';`
and all other svelte projects (i.e. via the vite cli), will still use this:
`import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";`

Would be great if you could confirn that this is working again for you now. Thanks!

**Comment by rudiv** [comment]
Perfect, all working now, at least on latest 👍

Not sure what the goal is of supporting older versions of SK (ie. ones that maybe still use svelte-preprocess)? I'm assuming just from a brief look that this would add in the vitePreprocess and leave the old preprocess import there, but rewriting the `preprocess` area?

For example, here's an older (~2 weeks) svelte.config.js with tailwinds added:
```
import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-node';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
		adapter: adapter()
	},

	preprocess: [
		preprocess({
			postcss: true
		})
	]
};

export default config;
```

Compared to the newer:
```
import adapter from '@sveltejs/adapter-node';
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
        // Consult https://kit.svelte.dev/docs/integrations#preprocessors
        // for more information about preprocessors
        preprocess: vitePreprocess(),

        kit: {
                // adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
                // If your environment is not supported or you settled on a specific environment, switch out the adapter.
                // See https://kit.svelte.dev/docs/adapters for more information about adapters.
                adapter: adapter()
        }
};

export default config;
```

**Comment by manuel3108** [comment]
That would indeed be great! Sadly im currently unable to put much dev work into this, but happy to review and merge a PR if anyone wants to!

**Comment by manuel3108** [comment]
As the time where this would have been the most useful is propably over now, I'm going to close this. But feel free to create PR for this!
