### ISSUE TITLE
Dependencies for Routify couldn't be resolved

### ISSUE THREAD

**Issue by BobRossCodes** [svelte-add/svelte-add#247]
`
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @roxi/routify@3.0.0-next.137
npm ERR! Found: vite@4.0.3
npm ERR! node_modules/vite
npm ERR!   dev vite@"^4.0.0" from the root project
npm ERR!   peer vite@"^4.0.0" from @sveltejs/vite-plugin-svelte@2.0.2
npm ERR!   node_modules/@sveltejs/vite-plugin-svelte
npm ERR!     dev @sveltejs/vite-plugin-svelte@"^2.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional vite@"^3.2.4" from @roxi/routify@3.0.0-next.137
npm ERR! node_modules/@roxi/routify
npm ERR!   dev @roxi/routify@"next" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vite@3.2.5
npm ERR! node_modules/vite
npm ERR!   peerOptional vite@"^3.2.4" from @roxi/routify@3.0.0-next.137
npm ERR!   node_modules/@roxi/routify
npm ERR!     dev @roxi/routify@"next" from the root project
`

**Comment by manuel3108** [comment]
Are you still able to reproduce that? I tried with the latest version and was unable to
