### ISSUE TITLE
Make idempotent

### ISSUE THREAD

**Issue by websocket98765** [svelte-add/svelte-add#25]
It'd be ideal if this checked whether it was run previously. Easiest way would probably be to check if `postcss.config.cjs` exists and already contains `tailwindcss`, and to abort the script if it exists. 

That would prevent it acting twice on the same code base, which will break a project until postcss.config.cjs is cleaned up again, overwrites a user's custom tailwind config, etc. (I intentionally ran the command twice to check if it was idempotent, with the below result for `postcss.config.cjs`).

```
const tailwindcss = require("@tailwindcss/jit");
const tailwindcss = require("@tailwindcss/jit");
const autoprefixer = require("autoprefixer");
const cssnano = require("cssnano");

const mode = process.env.NODE_ENV;
const dev = mode === "development";

module.exports = {
	plugins: [
		// Some plugins, like postcss-nested, need to run before Tailwind
		
		tailwindcss,
		
		// But others, like autoprefixer, need to run after

		// Some plugins, like postcss-nested, need to run before Tailwind
		
		tailwindcss,
		
		// But others, like autoprefixer, need to run after

		autoprefixer,
		
		!dev && cssnano({
			preset: "default",
		}),
	],
};
```

**Comment by babichjacob** [comment]
This should be fixed by 1fe58221bc2133c57e4ebf6f302b314d97a0a4d3. Closing this so that new issues can be made for specific situations where this doesn't work.
