### ISSUE TITLE
Add adder that enables breakpoints/debugging for Sveltekit server-side code (VS Code, WebStorm, etc)

### ISSUE THREAD

**Issue by Leftium** [svelte-add/svelte-add#255]
Apparently there is a [work-around](https://www.reddit.com/r/sveltejs/comments/11hsz5o/enable_vs_code_breakpointsdebugging_for_sveltekit/?utm_source=share&utm_medium=web2x&context=3) for the lack of proper Vite sourcemaps (https://github.com/sveltejs/kit/issues/7781, https://github.com/sveltejs/kit/issues/7320)

I think it would be simple to create an adder that does this. The changes required to the default Kit starter template should look like this: https://github.com/Leftium/vavite-node-loader-kit/commit/b3eae13da56fbdb74587c53631fdf9413ca9d444

(Note I haven't actually gotten this to work on my system, yet, but it may work for others...)

**Comment by benmccann** [comment]
This was requesting to install a Vite workaround, but it seems like workarounds are no longer necessary with the latest versions of Vite. Probably what we should do is update the SvelteKit docs. This doesn't seem involved enough to warrant an adder anymore.

Closing in favor of https://github.com/sveltejs/kit/issues/7320#issuecomment-2204294016
