### ISSUE TITLE
svelte-add bulma breaks on svelte typescript

### ISSUE THREAD

**Issue by Coded-Eye** [svelte-add/svelte-add#264]
> 'Log files:
> C:\Users\username\AppData\Local\npm-cache\_logs\2023-04-23T18_06_51_405Z-debug-0.log
> 
> # npm resolution error report
> 
> While resolving: website@0.0.0
> Found: typescript@5.0.4
> node_modules/typescript
>   dev typescript@"^5.0.2" from the root project
>   peer typescript@">=2.7" from ts-node@10.9.1
>   node_modules/ts-node
>     peerOptional ts-node@">=9.0.0" from postcss-load-config@4.0.1
>     node_modules/postcss-load-config
>       peerOptional postcss-load-config@"^2.1.0 || ^3.0.0 || ^4.0.0" from svelte-preprocess@4.10.7
>       node_modules/svelte-preprocess
>         dev svelte-preprocess@"^4.10.7" from the root project
> 
> Could not resolve dependency:
> peerOptional typescript@"^3.9.5 || ^4.0.0" from svelte-preprocess@4.10.7
> node_modules/svelte-preprocess
>   dev svelte-preprocess@"^4.10.7" from the root project
> 
> Fix the upstream dependency conflict, or retry
> this command with --force or --legacy-peer-deps
> to accept an incorrect (and potentially broken) dependency resolution.

Steps :
npm create vite@latest
- Selected framework : Svelte
- Selected variant : Typescript

Npx svelte-add@latest bulma

Npm install

---

Npm install give me the error above
Both --force and --legacy-peer-deps just gives me errors after I do npm run dev.

**Comment by manuel3108** [comment]
Duplicates #259
See there for a workaround.
