### ISSUE TITLE
Document option syntax for adders, e.g. to use cli tailwind-adder with forms, typography, daisyui

### ISSUE THREAD

**Issue by joelparkerhenderson** [svelte-add/svelte-add#269]
What is the syntax for using an adder and its options?

For example, the Tailwind adder says it has options `forms`, `typography`, `daisyui`.

How to include these options in the typical new project command such as:

```sh
npm create @svelte-add/kit@latest app -- --with tailwindcss
```

Thanks!

**Comment by manuel3108** [comment]
Thanks for reaching out!

Indeed, this is currently not documented anywhere, not in the adder itself, nor in this repo.

But using this command seems to work for me locally. Do you mind checking it out?

```
npm create @svelte-add/kit app -- --with tailwindcss --forms
```

And for my future self, this seems to be the relevant code: 
https://github.com/svelte-add/svelte-add/blob/cc097553c91f6150973c842707387e7b5aa73ece/projects/svelte-add/index.js#L177-L187

I'll leave that issue open for now, so that we can properly document this behavior!

**Comment by joelparkerhenderson** [comment]
Thanks for the quick reply. 

What I'm seeking please is the syntax for using any adder and any of its options.

Suppose adder "a" has options "b" and "c", and adder "d" has options "e" and "f". 

If I understand what you wrote above, is this the correct syntax?

```sh
npm create @svelte-add/kit app -- --with a --b --c --with d --e --f
```

If so, what's the process to add the syntax to the documentation?

When I try what you wrote, I'm not seeing how to run it as a test on a CI, such as with a before/after condition. Is there a testing process that I should be trying for the adders and their options?

Thanks!

**Comment by joelparkerhenderson** [comment]
Super, thank you so much. I never would've guessed that syntax. :-)

What I meant when I asked about test and CI, is approximately this... apologies in advance if you're already fully aware of what I'm about to write.

- Some programs have ways to download the program, then run local tests to verify the program behaviors work correctly on the local machine. For example, there could/should be a way to use a test to verify that the command line is correctly setting up Tailwind, PostCSS, etc. such as by checking a before-condition (e.g. no files exist) and an after-condition (e.g. the appropriate config files exist and contain the expected code).

- Some programs have ways to submit command lines to a remote testing service, such as a continuous integration service, or a sandbox service, which runs the commands, and does similar checking of a before-condition and after-condition.

- I personally like these kinds of tests a lot, because I like learning from them. I can see what the tests expect versus any actual output, and in my experience it's often easier/clearer for me to understand the test code than the program code-- which may be much more complex.

- I was asking if there are any tests like this, so I could read them and learn from them.

HTH. Thank you again for your fast response-- I am up and running now because of your help! 🚀

**Comment by manuel3108** [comment]
Great to hear, no problem for that :D

We still need to document that, but now that we have this issue, a lot of stuff is already done.

---

Ahh now I understand what you mean. Svelte Add currently has this feature in a way, but is currently not disposing this functionality publicly (as far as I'm aware at least.)

But after any adder was applied, svelte-add as it's own internal tests, to check what you suggest. Although some are pretty basic.

You will find them in the appropriate repos in the `__info.js` file. I have linked you the tailwindcss file in example: 
https://github.com/svelte-add/tailwindcss/blob/4c0f7323faeea7c529b37056c370a1947bbf3c77/__info.js#L39
