### ISSUE TITLE
Ignore .git in empty folder detection

### ISSUE THREAD

**Issue by chadulous** [svelte-add/svelte-add#285]
This is really straight forward, when checking if the directory is empty, .git should be ignored.

**Comment by manuel3108** [comment]
Good idea!
If anyone wants to do this, you could probably implement this somewhere here: 
https://github.com/svelte-add/svelte-add/blob/b1641b14075f97ca38358f478568b3a7cb2e1f04/projects/svelte-add/index.js#L599-L614

**Comment by mavthedev** [comment]
An even better implementation is if all directories/files that start with `.` are ignored except for things like `.prettierrc.*`

**Comment by manuel3108** [comment]
This does not occur in `svelte-add`s successor [`svelte-compose`](https://svelte-compose.com/), as we are handling things differently there.
