### ISSUE TITLE
Add option to remove svelte adder

### ISSUE THREAD

**Issue by geodic** [svelte-add/svelte-add#289]
## Problem
Currently, there seems to be no good way of removing a svelte adder other than either checking the source code of it and undoing the changes or completely revert to before you used the adder and build from there, which are both very inconvenient solutions.
## My Solution
The solution I'm envisioning is something like what GNU make and other build tools use, which is a separate uninstallation script that is tailored to the adder itself, so it is much better at its job. The disadvantage with this solution is that it adds extra work to the developer of the adder.

If no one volunteers, I might be able to take a shot at this.

**Comment by manuel3108** [comment]
Totally agree with your point! It would be really helpful if we could provide such tool, but currently I don't see a way to create this, without hugely increasing the maintenace overhead.

As described in the [readme](https://github.com/svelte-add/svelte-add#-safely-adding-integrations-and-examining-changes), currently the easiest way to do such a thing is to use `git`.

**Comment by manuel3108** [comment]
I don't think that from the current standpoint we will be able to implement this without a great efforts. As the readme already encourages you to use git to do such things as described in my last comment, I will be closing this issue.
