### ISSUE TITLE
Bootstrap Adder Lacks support for the new dark mode variables

### ISSUE THREAD

**Issue by Connor-Kelly** [svelte-add/svelte-add#295]
On installation via: `npx svelte-add@latest bootstrap` and `npm run dev`, I got an undefined reference to a scss variable: `$primary-text-emphasis-dark`.

This is contained in a new scss file: `_variables-dark.scss` @ `\node_modules\bootstrap\scss\_variables-dark.scss` as per [Bootstrap 5.3.0](https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/)
I fixed this locally by adding `@import 'bootstrap/scss/variables-dark';` to the `variables.scss` file in my src directory.

**Comment by manuel3108** [comment]
Thanks for bringing this to my attention. I have just added the missing import, and fixed another related bug when the user selected a JSDOC project.

Could you please make sure, that the newest version is working for you?

**Comment by Connor-Kelly** [comment]
Just got the chance to look at it again. Ran a new project, and it looks to work on my machine. Thank you!
