### ISSUE TITLE
[feat] Threlte

### ISSUE THREAD

**Issue by bobbymannino** [svelte-add/svelte-add#296]
Add an option for threlte

**Comment by manuel3108** [comment]
This has gotten a lot easier with the latest release of threlte. Here is the current doc: https://threlte.xyz/docs/learn/getting-started/installation

**Comment by bobbymannino** [comment]
It has indeed. Is it worth leaving open or shall I close it?

**Comment by manuel3108** [comment]
No absolutely leave this open. I had a try adding a few months ago, but there were so many ifs and thens that I did not finish it. 

Might be worth having another look now

**Comment by manuel3108** [comment]
As proposed in #314 we should drop support for svelte-cubed in the same time!

**Comment by grischaerbe** [comment]
If you need any guidance here, feel free to ping me 👍 I'd love to see this!

**Comment by manuel3108** [comment]
I'm currently working on a full rewrite of svelte-add and also giving the project a new name while i'm on it. 
I will hit you up if I need your help!
