### ISSUE TITLE
Feedback on the Tauri adder

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/svelte-add#3]
Lightweight electron competitor

Notes:
* https://github.com/mintterteam/vitejs-tauri-demo
* https://github.com/probablykasper/kadium

**Comment by Suyashtnt** [comment]
It's pretty simple from what I've done, just add it as a dep, run the installer and go

**Comment by Mattchine** [comment]
Since this is still a WIP. I have written the workflow needed to be done in my repos. [https://github.com/Mattchine/skitty](https://github.com/Mattchine/skitty)

**Comment by manuel3108** [comment]
This will be handled (again) by #338
