### ISSUE TITLE
Android support (deppendicies)

### ISSUE THREAD

**Issue by bato3** [svelte-add/svelte-add#30]
Please watch this issue status https://github.com/preset/cli/issues/73 and after it solved please update all templates deppendicy.

(I tested postcss and thailwindcss)

Thanks.

**Comment by babichjacob** [comment]
Sure.

**Comment by bato3** [comment]
Time to "paly"... https://github.com/preset/cli/releases/tag/v0.2.15

**Comment by babichjacob** [comment]
This should be fixed by 44b4d8dcc7f706925d6c552537723c51867cca64 making the latest `apply` version be used every time since it's no longer a dependency of the project (and is in the process of being more or less phased out).
