### ISSUE TITLE
Running svelte-add@latest tailwindcss improperly adds autoprefixer

### ISSUE THREAD

**Issue by YourFavoriteKyle** [svelte-add/svelte-add#300]
Running npx svelte-add@latest tailwindcss improperly adds autoprefixer to the posts.config.cjs plugins list.

What gets added:
```js
const tailwindcss = require('tailwindcss');
const autoprefixer = require('autoprefixer');

const config = {
	plugins: [
		//Some plugins, like tailwindcss/nesting, need to run before Tailwind,
		tailwindcss(),
		//But others, like autoprefixer, need to run after,
		autoprefixer
	]
};

module.exports = config;
```

Expected:
```js
const tailwindcss = require('tailwindcss');
const autoprefixer = require('autoprefixer');

const config = {
	plugins: [
		//Some plugins, like tailwindcss/nesting, need to run before Tailwind,
		tailwindcss(),
		//But others, like autoprefixer, need to run after,
		autoprefixer()
	]
};

module.exports = config;
```

Steps to reproduce:

1. Start a fresh svelte-kit project
2. Run npx svelte-add@latest tailwindcss

**Comment by manuel3108** [comment]
Hey there, thanks for the issue!

How did you determine that there is a pair of brackets missing? For me everything compiles without any errors, when those brackets are not present. Also, as far as I understand their [documentation](https://github.com/postcss/autoprefixer#webpack) it looks like you are not supposed to add those brackets.

**Comment by YourFavoriteKyle** [comment]
Hmm strange. After testing again it seems to be working as expected without the brackets.

> Also, as far as I understand their [documentation](https://github.com/postcss/autoprefixer#webpack) it looks like you are not supposed to add those brackets.

I missed this detail when looking at their documentation. Whoops!

> How did you determine that there is a pair of brackets missing?

I setup a fresh project, added some styles in src/app.postcss, and did not see those changes take effect. Adding those brackets there resolved the issue, leading me here. Today I do not have this issue though. This can probably be closed as it seems to be a me issue.
