### ISSUE TITLE
Running npx svelte-add@latest tailwindcss replayed 'Umlaute' and special Characters

### ISSUE THREAD

**Issue by Janny221199** [svelte-add/svelte-add#301]
Hey guys,

I used the command `npx svelte-add@latest tailwindcss` while installing Skeleton UI / Tailwindcss for an existing SvelteKit project.

Unfortunately all my german "Umlaute" like `ü` and speciel characters like `'` got replaced.

For example in my `src/routes/+layout.svelte` file I had the following lines of codes which got replaced to:

- `<li><a href="/flights">Flüge</a></li>` -> `<li><a href="/flights">Fl&#xfc;ge</a></li>`
- `<svelte:fragment slot="loading">{''}</svelte:fragment>` -> `<svelte:fragment slot="loading">{&apos;&apos;}</svelte:fragment>`

**I would have expected my files to remain unchanged.**

If you have any question please let me know!

Kind regards
Janny

**Comment by manuel3108** [comment]
Hey my german colleague, thanks for bringing this up. I don't know how I managed to miss that...

This is fixed the latest version released right now.
