### ISSUE TITLE
Could you use github releases

### ISSUE THREAD

**Issue by happysalada** [svelte-add/svelte-add#308]
it makes it easier to track the project and to package it for linux distributions.
Thank you for this package!

**Comment by manuel3108** [comment]
Sure, we can add this. What would you require to be part of the release? Do you need any special assets?

And if you have experience with that, feel free to provide a PR for the [release workflow](https://github.com/svelte-add/svelte-add/blob/main/.github/workflows/publish.yml)!

**Comment by happysalada** [comment]
just having a release that gives a brief overview of the changes and tags a particular commit is enough.
As a bonus it enables people to follow the changes in svelte-add!
I'm not sure I'll be able to find time, but if I do, I'll surely make a PR.

**Comment by manuel3108** [comment]
This is implemented for future releases now. According to the [Github CLI documentation] (https://cli.github.com/manual/gh_release_create) it should auto generate the release notes. The last commit did not have any meaningful commits, that's why the notes are currently looking pretty sad.,
