### ISSUE TITLE
Consider rename PostCSS files to *.pcss?

### ISSUE THREAD

**Issue by raymond-u** [svelte-add/svelte-add#311]
Rationale:

1. WebStorm can only [recognize PostCSS files in either `.pcss` or `.css`](https://github.com/JetBrains/intellij-plugins/blob/master/postcss/README.md). 
2. The PostCSS team appears to [recommend the usage of `.pcss` extension](https://twitter.com/PostCSS/status/661645290622083073)?

**Comment by manuel3108** [comment]
This seems like a good idea!
If anyone whishes to create a PR, i'm happy to accept it.

**Comment by manuel3108** [comment]
Thanks @raymond-u . This was published with the latest release. 

I made a few tweaks in the tailwindcss adder to represent the changes made here. Expect that, everything was fine.
