### ISSUE TITLE
Svelte-add removes `prettier-plugin-svelte` and replaces it with `prettier-plugin-tailwindcss`

### ISSUE THREAD

**Issue by shyakadavis** [svelte-add/svelte-add#318]
Hi.

First off, thanks for including `prettier-plugin-tailwindcss`. It was a chore doing it yourself.

That said, with the new release(s), using `svelte-add` to add tailwind, swaps plugins, and as a result, when I hit:

```
pnpm lint
```
I get the error
```bash
[error] Couldn't resolve parser "svelte".
 ELIFECYCLE  Command failed with exit code 1.
```

## Steps to reproduce:
1.
```
pnpm create svelte@latest test
```
2.
```
cd test && code .
```
Check your `.prettierrc` file. It should look like this
```
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100,
	"plugins": ["prettier-plugin-svelte"],
	"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```
4.
```
pnpx svelte-add@latest tailwindcss
```
Check your `.prettierrc` file again. It will look like this
```diff
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100,
-	"plugins": ["prettier-plugin-svelte"],
+	"plugins": ["prettier-plugin-tailwindcss"],
	"overrides": [
		{
			"files": "*.svelte",
			"options": {
				"parser": "svelte"
			}
		}
	]
}
```
Also, you can inspect your `package.json`. It effectively removes the `prettier-plugin-svelte`.

## Expectations
I want to have both plugins, so that in the end, it looks like this.
```diff
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100,
-	"plugins": ["prettier-plugin-svelte"],
-	"plugins": ["prettier-plugin-tailwindcss"],
+	"plugins": ["prettier-plugin-svelte", "prettier-plugin-tailwindcss"],
	"overrides": [
		{
			"files": "*.svelte",
			"options": {
				"parser": "svelte"
			}
		}
	]
}
```
---

I am more than happy to submit a P.R, if someone were so kind as to point me in the right direction. 🙂 

---
P.S. I am aware of this: https://github.com/svelte-add/svelte-add/issues/229, but having only one plugin breaks.
I think what should be inferred from Tailwind, https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins, is that they must be used at the same time, the only condition being that tailwind's plugin comes last.
If I'm missing something, or misunderstanding another, please let me know.

**Comment by manuel3108** [comment]
Thanks for submitting this, and sorry for letting you sit so long.

Your suggestion sounds logical and totaly makes sense. Not sure how I managed to miss that while merging the other feature last week. I'm pretty sure I build the application last week after applying the adder, but maybe I was in a different folder or something.

You will find information's on how to develop svelte add locally in the [README of this repo](https://github.com/svelte-add/svelte-add?tab=readme-ov-file#-developing-locally). The code you probably need to modify currently lives in another repo, that is included as git submodule into this repo. This will change in the future. The actual code you are probably interested in should be found around [here](https://github.com/svelte-add/tailwindcss/blob/main/__run.js#L324) if i see that correctly.

If there is anything unclear on how to develop or test that thing locally, please let me know!

Thanks for your help!

**Comment by shyakadavis** [comment]
Hi, @manuel3108 

I sent in a P.R, but I don't have confidence in what I've done, mainly because of the submodules. I have never touched them before, ergo, sad to report that I'm kinda blind here.

Please have a look and let me know your thoughts.

P.S. If I messed up, please feel free to close. 🙂

**Comment by manuel3108** [comment]
Hey!

I only see a [this](https://github.com/svelte-add/svelte-add/pull/319/files) PR right now. In there you only update the submodule reference, but I'm currently unable to find the code that you actually updated. You propably need to also create a PR in the [tailwindcss repo](https://github.com/svelte-add/tailwindcss) so that I can see the code you changed.

Don't bother about the submodule reference in this repo, I need to update it after merging the PR nevertheless.

Thanks for your work!

**Comment by manuel3108** [comment]
Hey @shyakadavis 

I just had another look at your account and the commit you provided and was unable to find a fork of the tailwindcss repo in your account. If it's easier for you, you can just fork that repo and commit the changes there. I can then take over from there on.

If you are currently unable to work on this, please let me know, than I can take this over for you. I just wan't to avoid doing work that has already been done. 

Thanks for your help!

**Comment by manuel3108** [comment]
Thanks to everyone for reporting and participating. A fix for this was momentarily published to npm.
