### ISSUE TITLE
Make a new Pugjs adder

### ISSUE THREAD

**Issue by killawabbit** [svelte-add/svelte-add#321]
The old community adder for Pugjs doesn't work since the svelte-add rewrite. I contacted the author of the community pugjs adder some time ago and only got a workaround description, but since their has been no uppdate. So, could you add an rewritten official Pugjs adder?

**Comment by benmccann** [comment]
We generally don't recommend folks use pug in their templates and even if you do want to I imagine it should be fairly easy to setup `svelte-preprocess`. I think this one would be better as a community adder and not something we'd officially support, so I'm going to go ahead and close it
