### ISSUE TITLE
Bootstrap JavaScript not included. Causes dropdowns to not work

### ISSUE THREAD

**Issue by EduMenges** [svelte-add/svelte-add#327]
Any element requiring Popper.js functionality like dropdowns is broken. To reproduce, simply create a new svelte app, use the Bootstrap add, and paste this snippet in `+page.svelte`:

```html
<div class="dropdown">
  <button
    class="btn btn-secondary dropdown-toggle"
    type="button"
    data-bs-toggle="dropdown"
    aria-expanded="false"
  >
    Dropdown button
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>
```

Clicking in the dropdown does not show any menus.

**Comment by manuel3108** [comment]
Hey @EduMenges 
thanks for reporting this.
I'm not fully comfortable with bootstrap so please help me if I jump from to the wrong conclusions or ask not so good questions!

First of all I would like to know, how you jumped to the conclusion that this is a problem with `popper.js`.
The only thing I can currently imagine, is that you have read the following in the [adders readme](https://github.com/svelte-add/bootstrap):
> The [@popperjs/core package](https://www.npmjs.com/package/@popperjs/core) is installed to satisfy bootstrap's peer dependency on it. You can safely ignore it, or uninstall it if you can do so without introducing package manager errors.
But from my understanding this lib was only added, to satisfy all `npm install` dependencies.

After a lot of trying around, I can confirm this bug. As far as my understanding goes the easiest way to make this work is by modifying the `+layout.svelte` like this:
```svelte
<script>
	import { onMount } from "svelte";
	import "../app.scss";
	import { browser } from "$app/environment";

	onMount(async () => {
		if (!browser) return;

		await import("bootstrap");
	});
</script>

<slot />
```


Does this work for you? Do you have a better implementation that works?

**Comment by EduMenges** [comment]
@manuel3108 Your solution works for me, this issue can be closed from in my point of view.

**Comment by manuel3108** [comment]
@EduMenges Thanks for the confirmation. I will leave this open until this is properly implemented into the adder.

As you mentioned above, the above behaviour causes confusion and does not seem to be entirely correct.

**Comment by omundy** [comment]
@manuel3108 Your solution also works to open the mobile nav. However, it does not collapse after clicking. https://omundy.github.io/givememydata/

**Comment by manuel3108** [comment]
Hey! Did you already change anything @omundy ?
Because for me it's working on my phone and in the chrome mobile view on my desktop.

**Comment by omundy** [comment]
That's odd because the nav stays open on desktop and my phone for me (both Chrome incognito). I haven't changed anything with the nav.

**Comment by siccovansas** [comment]
I've had issues getting the JavaScript part of Bootstrap to work in SvelteKit as well.

Using svelte-add to add Bootstrap and then changing `+layout.svelte` as shown by @manuel3108 in [this comment above](https://github.com/svelte-add/svelte-add/issues/327#issuecomment-1868851277) indeed seems to work.

I've created a [SvelteKit REPL](https://stackblitz.com/edit/sveltejs-kit-template-default-1dtewr?file=src%2Froutes%2F%2Blayout.svelte) with a working Bootstrap dropdown. I created this REPL using the files I get when I run `npm create @svelte-add/kit@latest my-new-svelte-kit-app -- --with bootstrap`, changing `+layout.svelte` as shown in [the comment above](https://github.com/svelte-add/svelte-add/issues/327#issuecomment-1868851277) and copying the code for the [first Bootstrap dropdown example](https://getbootstrap.com/docs/5.3/components/dropdowns/#single-button) to `+page.svelte`.

**Comment by siccovansas** [comment]
I upgraded the REPL from my previous comment with examples of [all Bootstrap components that require JavaScript](https://getbootstrap.com/docs/5.3/getting-started/introduction/#js-components):

- [New REPL](https://stackblitz.com/edit/sveltejs-kit-template-default-7lsttm?file=src%2Froutes%2F%2Blayout.svelte,src%2Froutes%2F%2Bpage.svelte) with examples of all Bootstrap JS components.

The only two components that I can't get to work are Toasts and Tooltips/Popovers (as shown of the bottom of the new REPL).

@manuel3108 (or anyone else) can you get those to work?

**Comment by manuel3108** [comment]
@siccovansas Thanks for your work!

You were 99% there! The last clue is to use this dynamic import statement:
```js
const bootstrap = await import("bootstrap");
```

instead of just 
```js
await import("bootstrap")
```

(I have updated my comment above, including the last details you found out!)

**Comment by omundy** [comment]
> @manuel3108 (or anyone else) can you get those to work?

@siccovansas  The Navbar collapse does not work on Chrome desktop when clicking a link.

**Comment by siccovansas** [comment]
Thanks @manuel3108! I added `const bootstrap = await import("bootstrap");` and indeed all Bootstrap JS components now work :fireworks:! I've updated the REPL.

Can this code be added to the Bootstrap adder or are there still things (I can help) to test?

@omundy, I just tested Navbar collapse in Chromium (on Ubuntu) and I can't see anything wrong with it. Can you describe your issue more precisely? Which exact link do you click and what doesn't work then?

**Comment by manuel3108** [comment]
This is supported by `svelte-add`s successor [`svelte-compose`](https://svelte-compose.com/)

[Bootstrap composer](https://svelte-compose.com/composer/bootstrap/)
