### ISSUE TITLE
Deprecate imagetools adder

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#330]
I wouldn't suggest that anyone should use imagetools directly. It's too low-level. They'd be better of using `@sveltejs/enhanced-img`, which is built on top of it and takes care of a lot of the complication: https://kit.svelte.dev/docs/images

It's probably make sense to just archive the imagetools adder and remove it from the readme

**Comment by manuel3108** [comment]
Done, thanks!
