### ISSUE TITLE
Archive routify adder?

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#331]
The routify docs say to get started with:
```
npm init routify@latest
```

It seems odd then that we'd have a routify adder because I don't expect folks would create a vanilla Vite project and run the routify adder rather than just running `npm init routify@latest` as the Routify docs suggest.

**Comment by manuel3108** [comment]
Up until now (routify v2) the cli command you mentioned only worked to create a new project. 
I have made a quick test with v3, and it looks as it's basically using the same cli, so this also only works for new projects.

If you already have a project setup, it appears to be just overriding your existing files, basically destroying your project setup. At least that's what I experienced.
