### ISSUE TITLE
state of `svelte-add`

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-add#334]
`svelte-add` has some major issues, most of them are properly outlined in #328 for those interested. These issues cannot be handled correctly, without rewriting most of the codebase.

With the help of #328 that's exactly what I decided to do, and it's time to share the progress with everyone. 

Based on the rewrite I was also able to add small [website](https://svelte-add.com/) in order to improve the visibility of different adders and increase the composability of different adders. For the sake of simplicity let's call the rewrite `v2`

### `@svelte-add/create-kit` and `@svelte-add/create-vite` are now deprecated. What should I use now.
You can simply just use the `svelte-add` package with `npx svelte-add`. The functionality of creating new project if no valid project was detected was now backed in into the core package.

### Adder `xxx` does not exist anymore
Adders have been ported by relevance. The adders with the most stars in their respective github repository were ported to `v2`. In order to reintroduce the adder, it need's to be ported. In order to start the process, please consider creating a [new issue requesting a new adder](https://github.com/svelte-add/svelte-add/issues/new?assignees=&labels=C%3A+new-adder%2CT%3A+adder&projects=&template=new_composer.yml)

If you need to be able to use the old version of `svelte-add` to get your project up to speed, consider using `npx svelte-add@2024.4.9-0.0`

### How to migrate syntax from the previous `svelte-add`
If you are still using syntax like this `npx svelte-add@latest --with bulma+mdsvex`, please consider the configurator inside the [website](https://svelte-add.com/) to generate the new syntax.

## Other notable changes
* We moved away from submodules. They are horrible for maintainers, and even worse for contributors. We now use a monorepo.
* A website as a main entry point, always displaying the latest adders: https://svelte-add.com/ and support cli command configuration.
* Automatic release management
* Other usual rewrite stuff: maintainability, extensibility, etc.

**Comment by benmccann** [comment]
Cool to see work happening on the rewrite! I hate git sub-modules, so happy about that part particularly 😆  Having a website is a nice addition as well.

The only thing that gives me pause is losing the svelte-add name, which is well-known in the community and nice and concise. `svelte-compose` is a bit longer and doesn't have the same ring to it. Could we just publish new versions keeping the `svelte-add` name or using the `@svelte-add` scope?

**Comment by manuel3108** [comment]
Sometimes things are just too obvious to see them by yourself. Up until your comment I was under the impression that this would not be possible, because I don't have access to the NPM Org, but it didn't came to my mind to just request access. That's what I have just done.

If everything works as I expect, this is the new plan!

**Comment by manuel3108** [comment]
Hey @babichjacob, hope you don't mind the ping. Would you mind adding me (manuel3108) to the NPM org?

Thanks for your help!

**Comment by babichjacob** [comment]
No problem, I've sent you an invite!

Sorry for my absence 😰

**Comment by manuel3108** [comment]
@J Wow, that was a fast one. No problem at all. Thank you

**Comment by manuel3108** [comment]
@babichjacob Totally forgot about https://www.npmjs.com/package/svelte-add, could you do the same there?

**Comment by babichjacob** [comment]
I added `svelte-add` to the organization, I think, did that work?

**Comment by manuel3108** [comment]
Yes, that worked, thanks!

**Comment by dummdidumm** [comment]
Hi @manuel3108, Svelte maintainer here 👋 We have interest in making `svelte-add` a bit more official/formal. Are you available for a chat on the Svelte Discord to discuss details? If so, just put a message in the `#contributing` channel and we can take it from there.
