### ISSUE TITLE
semantic-release with support for Github/npm

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-add#340]
# Website
https://semantic-release.gitbook.io/semantic-release

# Documentation
https://semantic-release.gitbook.io/semantic-release

# Integration summary
1. Install the following dependencies: `semantic-releae`, `@semantic-release/commit-analyzer`,                 `@semantic-release/npm`, `@semantic-release/github`, `husky` and `lint-staged` (see notes below) 
3. modify `package.json` and the following section: 
```json
        "release": {
                "plugins": [
                        "@semantic-release/commit-analyzer",
                        "@semantic-release/release-notes-generator",
                        "@semantic-release/github"
                ],
                "branches": [
                        "main",
                        "next"
                ]
        },
        "lint-staged": {
                "**/*.{js,jsx,ts,tsx,html,css,json}": [
                        "pnpm run format"
                ]
        }
}
```
5. Also add the following scripts to `package.json`:
```json
                "lint": "prettier --check . && eslint .", 
                "lint-staged": "lint-staged",
                "format": "prettier --write .",
                // setup husky
                "prepare": "husky",
                // ensure everyone has commit hooks set up
                "postinstall": "pnpm run prepare",
                // actual semantic-release script 
                "release": "semantic-release"
```

6. Add the following to `.husky/pre-commit'
```bash
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# dlx downloads "lint-staged" every time, resulting in long commit delays
# when internet connection is slow
# Solution: Install as dev dependency and run as target from package.json instead
pnpm run lint-staged
```

7. Add the following to Github actions (further configuration for repository permissions is required)
```yaml
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Publishing to NPM is not necessary for websites
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release
```

# Further details 
## Explanation
This request is augmenting the Github pages composer. 

As a note ahead, the formatting and linting might be a seperate composer. It is just how I did it. 

Setting up a Continuous Integration, Delivery and Deployment pipeline can take several hours per repository. 

Using Conventional Commits and `semantic-release` can help to fully automated the process, including
- automated semantic versioning
- tagging in Git 
- publishing a release to npm or Github pages
- Release notes on Github 

The composer should take over additional tasks to ensure a consistent and productive development experience:
- check format of commit messages using `husky`
- Lint and fix any changed files using `lint-staged` for consistent formatting using `prettier` (shipped with sveltekit) 

## Options 
Ask for
- github and npm plug-ins of semantic-releae
- ask for lint-staged, and husky

## Configure Github Actions

The Github Actions are already configured to build and deploy the project to Github Pages.

Therefor you need to set two permissions in the settings of your repository:

- In your browser, open the repository settings
- Go to the **Actions** section
- In the **Workflow permissions**, select _Read and write permissions_
- Check _Allow GitHub Actions to create and approve pull requests_

**Comment by manuel3108** [comment]
Initially brought up by @tburny in https://github.com/svelte-compose/svelte-compose/issues/22

**Comment by AdrianGonz97** [comment]
is this meant to be an adder? or is this meant for this repo? if the latter, then I think changesets are a fine enough solution for this. if it's the former, then i feel it's out of the scope of being a "svelte adder"

**Comment by manuel3108** [comment]
It was meant as the first one. Now that we have a clearer image on what svelte-add is and will be, I totally agree. Therefore closing.
