### ISSUE TITLE
Adjust the opt-out behavior of CLI flags

### ISSUE THREAD

**Issue by AdrianGonz97** [svelte-add/svelte-add#350]
### Topic

applies to all adders

### Description

It would be preferable if the CLI flags were designed to be **opt-in** rather than **opt-out**.

One can imagine that when a couple of more plugins are added, it would quickly become cumbersome to add all of these opt-out flags just to avoid the CLI wizard:

```
npx @svelte-add/tailwindcss@latest --typography false --forms false --scrollbars false --other-plugin false --one-last-one false
```

### Describe the solution you'd like

Instead, it should be the inverse, where adding the flag includes the addon/plugin:
```
npx @svelte-add/tailwindcss@latest --typography --forms
```

### Alternative

An alternative could be to include a `--none` flag to preserve the default state of running through the CLI wizard, but also not having to add all of the flags to avoid it either:
```
npx @svelte-add/tailwindcss@latest --none
```

**Comment by manuel3108** [comment]
The problem I see with 

```sh
npx @svelte-add/tailwindcss@latest --typography --forms
```

is that this 

```sh
npx @svelte-add/tailwindcss@latest
```

would implicitly assume that all options are false / fallback to the default value and that this would not trigger the interactive cli.

That's why I would currently prefer the your suggested alternative, although I'm not sure if `--none` would represent the correct meaning. Maybe something like `--default` would be a better fit

**Comment by AdrianGonz97** [comment]
Agreed, `--default` is definitely the better fitting name and solution.

**Comment by manuel3108** [comment]
Please do not consider working on this until #368 is merged, as it was necessary to rewrite major amounts of the `execute.ts` file (not commited), which would cause massive merge conflicts and create unnecessary work.
