### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by bato3** [svelte-add/svelte-add#359]
### Topic

[Prisma ](https://github.com/svelte-add/svelte-add/issues/248)(database)

### Description

The standard addition process requires selecting which database engine will be used. This is possible through parameters. But it would be nice if a DSN (connection string) was created along the way.

BTW: is possible to run command?

BTW2: Is possible to display message to usser? (eg.: *Run command `xxxxx` to finish proces*)

### Describe the solution you'd like

I believe the adding process should be interactive, just like creating a Svelte/SvelteKit project.

Parameters may seem much faster, but the process of adding them is not frequent enough to force us to search for a list of parameters.

Additionally, in interactive mode you can create more complex adders.

**Comment by manuel3108** [comment]
Relates #248 

> BTW: is possible to run command?

What do you mean here? Would you like to execute an external node command to initiate the setup of another tool? If that's the case, see the storybook adder, this is already supported (Line 20)
https://github.com/svelte-add/svelte-add/blob/a980a2c5ac1c1ebf3524328cfc790dcab19e1ebd/adders/storybook/config/adder.js#L5-L23

> BTW2: Is possible to display message to usser? (eg.: _Run command `xxxxx` to finish proces_)

This is not currently possible, but would probably be a nice addition

> I believe the adding process should be interactive, just like creating a Svelte/SvelteKit project.
> 
> Parameters may seem much faster, but the process of adding them is not frequent enough to force us to search for a list of parameters.
> 
> Additionally, in interactive mode you can create more complex adders.

I'm not entirely sure what you mean. It's already possible to execute an adder in interactive mode. You can just omit all parameters like this `npx @svelte-add/bootstrap@latest`

If you want to interactively choose all tools that you want to add, you can already use `npx svelte-add@latest`

**Comment by manuel3108** [comment]
missing author feedback.
