### ISSUE TITLE
add `typescript-svelte-plugin` support

### ISSUE THREAD

**Issue by ryoppippi** [svelte-add/svelte-add#369]
### Topic

typescript config

### Description

I install the typescript-svelte-plugin every time I create a Sveltekit project with npm create svelte. I've been doing that for the last year and a half and it's very time-consuming!

### Describe the solution you'd like

Please add support for `typescript-svelte-plugin` like `npx svelte-add --addr tsconfig`

Related https://github.com/sveltejs/kit/issues/12228

**Comment by benmccann** [comment]
Per https://github.com/sveltejs/kit/issues/12228#issuecomment-2118850582 it would be discouraged to add this as part of your project and you should instead add it as part of your editor setup, so I don't think we should have an asset for this

**Comment by ryoppippi** [comment]
idk why it is not good to add just a single command
Why don't you care non-VSCode users?? @benmccann

**Comment by ryoppippi** [comment]
I planned to implemente it so opened this issue, why closed?
