### ISSUE TITLE
spawn pnpx ENOENT

### ISSUE THREAD

**Issue by takoyaro** [svelte-add/svelte-add#38]
While running `npx svelte-add tailwindcss` , I get the following error:
```js
 errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn pnpx',
  path: 'pnpx',
  spawnargs: [
    '--yes',
    '--ignore-existing',
    'apply',
    'svelte-add/tailwindcss',
    '--jit',
    'false',
    '--no-ssh'
  ]
```

I figured there might be something wrong with my environment since I also happen to have pnpm installed and tried running:
`pnpx svelte-add tailwindcss` but still end up with the same error.

Command was running fine yesterday though, must have been caused by recent updates.

**Comment by babichjacob** [comment]
> Wait, are you on Windows? This may be related to https://github.com/ionic-team/capacitor-angular-toolkit/pull/11/files

I get the mentioned error on Windows too. Following this linked pull request indeed solves it. Hold tight while I fix this; it might take a few hours or days given that I want to do it properly.

**Comment by evan-thurston** [comment]
> Hold tight while I fix this; it might take a few hours or days given that I want to do it properly.

Is there a workaround for this in the meantime?

**Comment by babichjacob** [comment]
> > Hold tight while I fix this; it might take a few hours or days given that I want to do it properly.
> 
> Is there a workaround for this in the meantime besides without a virtual machine?

There is no workaround, so let's hope I can get this done within this hour.

**Comment by babichjacob** [comment]
This fix works for me. Thanks for the report and patience!

**Comment by f-elix** [comment]
@babichjacob Thank you so much for your work, you were incredibly quick in figuring this out and fixing it! Please know that this is really appreciated.
