### ISSUE TITLE
chore: Revert storybook adder back to `@latest` when `v8.3.0` releases

### ISSUE THREAD

**Issue by AdrianGonz97** [svelte-add/svelte-add#386]
### Topic

storybook

### Description

As of #384, we've changed the storybook version to use the `@next` tag as it fixed a the bug described in #358. When `8.2.0` releases, we should revert the adder back to using `@latest`.

### Describe the solution you'd like

- [x] Swap `@next` tag for `@latest`
- [x] Remove `--legacy-peer-deps` flag from `npm install`: https://github.com/svelte-add/svelte-add/commit/668c6c797b27b09b752841aaebdeb8c8a58af2f4

**Comment by benmccann** [comment]
We should also remember to remove the `--legacy-peer-deps` flag: https://github.com/svelte-add/svelte-add/commit/668c6c797b27b09b752841aaebdeb8c8a58af2f4

**Comment by benmccann** [comment]
They said the fix is in 8.1.8, so we should be able to try `latest` again

**Comment by manuel3108** [comment]
@benmccann This is apparently not the case, or it's still not working as expected.
See #393, or better my [small repro workflow run](https://github.com/manuel3108/storybook-missing-packages-repro/actions/runs/9503757087/job/26194895861), which clearly shows that 8.1.8 is used, but without any changes in the output.

Interestingly enough that PR [appeared in the Changelog for 8.1.8](https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md), but seems to be [re-included for the changelog for 8.1.9](https://github.com/storybookjs/storybook/pull/28231)

**Comment by manuel3108** [comment]
See #393 

In summary, `8.2.5` fixes some issues, but introduces other. As the currently published way is broken, let's still use `next` for now. Leaving this issue open for the same reason.
