### ISSUE TITLE
Don't offer to add Routify to SvelteKit projects

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#394]
### Topic

routify

### Version

2.0.10

### Expected behavior

It doesn't really make sense to setup routify on a SvelteKit project, so that one should just be left out of the list of options. We could probably check if `@sveltejs/kit` is in either `dependencies` or `devDependencies`

I almost wonder if we should just remove the Routify adder. [SvelteKit has 50x more usage](https://npmcharts.com/compare/@roxi/routify,@sveltejs/kit?log=false&interval=30) and is the officially recommended solution. With svelte-add becoming more official it feels a little weird not to offer an option for the one we recommend folks use and offer an option for another one

### Actual behavior

When I run `npx svelte-add`, it offers to add mdsvex, routify, and Threlte as tools

**Comment by manuel3108** [comment]
I think this is a continuation of a bug we found yesterday, see #387

We should first fix the bug either way, as this would also happen with the new drizzle adder the other way around.

After fixing that we should be able to remove the routify adder.
