### ISSUE TITLE
Unexpected token '??='

### ISSUE THREAD

**Issue by mhm9002** [svelte-add/svelte-add#40]
running any of svelte-add on a fresh svelte project causes the following error;

npx svelte-add svelte-add/bulma

npx: installed 61 in 7.083s
(node:5478) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:141:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5478) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5478) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by babichjacob** [comment]
Duplicate of https://github.com/svelte-add/svelte-add/issues/41
