### ISSUE TITLE
Single screen CLI

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#410]
### Topic

svelte-add

### Description

I'd had an idea for including headers in the CLI select described in https://github.com/bombshell-dev/clack/issues/197. That can't be implemented without support in `@clack/prompts`, so I've been trying to think how we can get closest to that with the current CLI APIs.

This would help group items without adding screens and as well as help users see very quickly what type of thing each library does.

### Describe the solution you'd like

An idea I had that I think could be cool would be to make the CLI look something like:
```
┌  Welcome to Svelte Add
│
◇  What would you like to add to your project?
│  ◻ CSS              | Bootstrap
│  ◻ CSS              | Bulma
│  ◻ CSS              | TailwindCSS
│  ◻ DB               | Drizzle
│  ◻ Markdown         | mdsvex
│  ◻ UI development   | Storybook
└
```

**Comment by manuel3108** [comment]
I like that idea, I think it makes a lot of sense the way you have structured that.

**Comment by benmccann** [comment]
I tried taking a stab at it over the weekend, but couldn't figure out how the pieces fit together in terms of how the questions were being generated for the main `svelte-add` CLI, so I might have to leave this one to you or @AdrianGonz97 if you guys like the idea.
