### ISSUE TITLE
Decide how to have DB and auth adders interact with each other

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#411]
### Topic

drizzle/lucia

### Description

I feel like the next adder we should add should potentially be for auth. Maybe Lucia (https://github.com/svelte-add/svelte-add/issues/297)

The auth providers and DB providers might interact with each other. E.g. to save auth info to the database. And Lucia has a Drizzle integration. But this provides a tricky challenge of what order to we run things in. Or what if a user runs one. And then later comes back and runs the other

### Describe the solution you'd like

We might have to define some sort of interface for these things to adhere to

**Comment by manuel3108** [comment]
That's a pretty tough challenge as adders are planned to be run completely independently. 
We might be able to add some sort of config `runsBefore: ["lucia"],`. That way it would still be the job of core to handle those conflicts. 

If `drizzle` would run before `lucia` we could make the lucia adder check if `drizzle` is part of the dependencies inside the `package.json`. 

That could work without too much effort in my opinion, but might not be as flexible for the future.

**Comment by benmccann** [comment]
Hmm, I just realized these aren't the only ones that will interact. I was thinking about porting over the ones from `create-svelte`, which are vitest, playwright, eslint, and prettier. There are some that interact, which can be seen here: https://github.com/sveltejs/kit/tree/main/packages/create-svelte/shared.

I think `create-svelte`'s setup has some nice properties, but I wouldn't necessarily do everything the way that is done there.  One thing it has that is really nice is that you can have a folder where any files in it are copied over including merging in the `package.json` in that directory.

One thing that might be easier with `svelte-add`'s code-based approach is some of the interactions like this one: https://github.com/sveltejs/kit/blob/main/packages/create-svelte/shared/%2Bplaywright%2Bvitest/package.json. That's not really a true interaction. It's just saying that if there's already a `test` field then run those existing tests in addition to the new ones. It's not necessarily a true interaction - though you would need that logic in both the playwright and vitest adders.

I think the one real interaction we have is that if you already have eslint or prettier and then run the other one then you should add `eslint-config-prettier`: https://github.com/sveltejs/kit/blob/5645614f497931f587b7cb8b3c885fce892a6a72/packages/create-svelte/shared/%2Beslint%2Bprettier/package.json#L3

Perhaps, at least for official adders, we can do something like detect existing functionality and then if that functionality and the requested functionality have an interaction we can apply that combo. But I don't know if we'd want to create a `@svelte-add/drizzle+lucia` or maybe `@svelte-add/db+lucia`. I feel like that might create quite a few extra packages. I wonder if we even necessarily need separate packages for all the adders as opposed to just a directory per adder because I think the adders all get downloaded all the time anyway?

**Comment by manuel3108** [comment]
> I think the one real interaction we have is that if you already have eslint or prettier and then run the other one then you should add `eslint-config-prettier`: https://github.com/sveltejs/kit/blob/5645614f497931f587b7cb8b3c885fce892a6a72/packages/create-svelte/shared/%2Beslint%2Bprettier/package.json#L3

Let's imagine that we would be the `eslint` adder in that case, located in `./adders/eslint/config/adder.ts`, then this is how I could imagine it to work
```js
export const adder = defineAdderConfig({
    // metadata and stuff like this
    packages: [
        { name: 'eslint', version: '^x.y.z', dev: true },
        {
            name: 'eslint-config-prettier',
            version: '^x.y.z',
            dev: true,
            condition: ({ devDependencies, addersToInstall }) =>
                // dev dependencies from `package.json`.
                // allows us to detect if prettier has been 
                // installed in previous runs (maybe days earlier)
                devDependencies.includes('prettier') ||
                // list of adder ids that the user selected in the 
                // cli in his current run. This allows us to prevent
                // running adders in the wrong order
                addersToInstall.includes('prettier'),
        },
    ],
    files: [
        {
            name: () => `package.json`,
            contentType: "json",
            content: ({ data }) => {
                const runEslintCommand = "eslint .";
                if (data.scripts.lint) data.scripts.lint += ` && ${runEslintCommand}`;
                else data.scripts.lint = runEslintCommand;
            },
        },
        {
            name: () => `eslint.config.js`,
            contentType: 'script',
            content: ({ data, options }) => {
                /* */
            },
        },
    ],
});

```

That was my first thought at least.

Until I searched how the eslint config itself was being generated: https://github.com/search?q=repo%3Asveltejs%2Fkit+path%3A%2F%5Epackages%5C%2Fcreate-svelte%5C%2F%2F+eslint.config.js&type=code

But as far as I can see, we should still be able to achieve that with a similar config like above. The only important point would be that we don't want to duplicate the same code for the `eslint.config.js` inside the eslint and prettier adders. But since we are bundling the code anyway, we should just be able to extract functions into a common place, that both adders reference.

> I wonder if we even necessarily need separate packages for all the adders as opposed to just a directory per adder because I think the adders all get downloaded all the time anyway?

See #441

**Comment by AdrianGonz97** [comment]
> We might be able to add some sort of config `runsBefore: ["lucia"],`. That way it would still be the job of core to handle those conflicts.

I think this would be a good way to do it. However, I'd prefer it being a `runsAfter` config option, letting the dependent choose the running order rather than the dependency (i.e. the adder that needs to execute in a certain order should be the one that states it) In the case of `drizzle` and `lucia`, `lucia` is really the adder that cares while `drizzle` is mindless to it

**Comment by manuel3108** [comment]
Do we actually need to make this an array? Wouldn't `runsAfter: "prettier"` be enough in 99% of the time? Making this an array would dramatically increase the complexity of determinating the correct order. Additionally this might cause impossible cases

**Comment by AdrianGonz97** [comment]
sure, let's just have it work for what we need right now. in the future, if an adder needs to depend on more than 1, we can always tweak the implementation to add support for it later
