### ISSUE TITLE
Create/update `.env.example`

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#417]
### Topic

drizzle

### Description

The drizzle adder creates an `.env` file. However, if someone new on the team checks out the project, they won't have that file because it's ignored by git, which leaves them in a tough place.

### Describe the solution you'd like

Create/update both the `.env` and `.env.example` files

Should probably merge https://github.com/svelte-add/svelte-add/pull/416 first to avoid a merge conflict

**Comment by manuel3108** [comment]
What would you expect to be in that `.env.example` file? Exactly the same content as when the `.env` file is generated? The default files does not seem to include any usernames

**Comment by benmccann** [comment]
> What would you expect to be in that .env.example file? Exactly the same content as when the .env file is generated? 

Yeah, I think so.

For reference, the `.env` file contains:
```
DATABASE_URL="postgres://root:mysecretpassword@localhost:5432/local"
```
