### ISSUE TITLE
Consider not publishing each adder individually to npm

### ISSUE THREAD

**Issue by manuel3108** [svelte-add/svelte-add#441]
### Topic

all adders

### Description

Currently we are publishing all adders seperatly to npm (`@svelte-add/tailwindcss`). Additionally they are bundled into the `svelte-add` cli.

Initially this was done to provide an easy to use command to install a single adder. With some of the latest changes we have done lately, this has probably become way more unimportant. Let's compare the two possibilities to apply the tailwindcss adder.
```
pnpm dlx @svelte-add/tailwindcss@latest
```

vs.
```
pnpm dlx svelte-add@latest tailwindcss
```

As of now, both commands contain exactly the same words and have nearly exactly the same number of characters (second is one character shorter). To me the second one feels more natural and would also bring the benefit, that you already know the command for the interactive cli by heart, in case you need it at some point

```
pnpm dlx svelte-add@latest 
```

---

Additionally this could remove the need of the peer dependencies here and solve some of the challenges we had with changesets in the past: https://github.com/svelte-add/svelte-add/blob/b42e0a0169a717b9381843e0689d135a64c3f1f3/packages/cli/package.json#L20-L26

### Describe the solution you'd like

We will need to think of we can properly represent this in the repo, while still keeping some flexibility for #411 . We might want to create a new private package `@svelte-add/adders` that lives in the `./adders` directory. This will work because the adders are bundled into the cli in either way. 

The only thing I'm unsure about is if changesets would still work as we expect in this configuration. We might need to give it a try to find that out.

**Comment by AdrianGonz97** [comment]
>Initially this was done to provide an easy to use command to install a single adder. 

oh! I was under the impression that each adder had their own discrete npm package for the purposes of package size savings. Although, looking at the package sizes and dependency graph of [`svelte-add`](https://npmgraph.js.org/?q=svelte-add#select=exact%3Asvelte-add%402.2.1&sizing=) vs a [single adder](https://npmgraph.js.org/?q=%40svelte-add%2Ftailwindcss#sizing=&select=exact%3A%40svelte-add%2Ftailwindcss%401.0.15), that doesn't seem to be the case 😅 

The only noticeable difference is the bundled modules of the adders themselves (219KB vs 61KB), which will continue to scale up the more adders we add. Perhaps that's something to consider? However, in the grand scheme of things, the total download size with dependencies is 21MB (to which I think can be considerably lowered), making their differences relatively small.

Despite that, I'm in favor of only publishing a single CLI. It lowers of the cognitive load for users and would also simplify our build process by a bit.

> The only thing I'm unsure about is if changesets would still work as we expect in this configuration. We might need to give it a try to find that out.

I think it'll be fine. I don't really see any problems that could arise from it
