### ISSUE TITLE
Align lines and letters in CLI

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#442]
### Topic

svelte-add

### Version

2.3.0

### Expected behavior

I did this in photoshop, so don't have the code for it unfortunately :laughing: 

![aligned](https://github.com/svelte-add/svelte-add/assets/322311/e9b5d3d8-fe52-47f9-b572-db1eb466cbc1)

### Actual behavior

![Screenshot from 2024-06-24 12-19-33](https://github.com/svelte-add/svelte-add/assets/322311/bac62c0b-bb6d-4423-abd6-426dfdb22ee0)

**Comment by benmccann** [comment]
As another option, what we just remove the lines? Rich pointed out that they're a bit noisy visually and I agree

![no-lines](https://github.com/svelte-add/svelte-add/assets/322311/5058fb2d-075c-42cc-b541-ea5ffef9ba0a)

**Comment by AdrianGonz97** [comment]
Fair point since the original purpose of the lines is to highlight the group when the group header was selected like so:
![img](https://i.imgur.com/8U6wY36.png)

**Comment by benmccann** [comment]
One more improvement we came up... :laughing: I think adding a new line above each category as well looks even nicer

![no-lines-newlines](https://github.com/svelte-add/svelte-add/assets/322311/c3956e0b-6a2f-46fc-871f-585c462aa1cd)

**Comment by AdrianGonz97** [comment]
> One more improvement we came up... 😆 I think adding a new line above each category as well looks even nicer

that one might take a bit to figure out 😅 using a `\n` makes it a bit hideous as the spacing is way too wide - not sure if there's ways to control the line height more granularly but i'm looking into it
