### ISSUE TITLE
BiomeJS

### ISSUE THREAD

**Issue by MordechaiHadad** [svelte-add/svelte-add#454]
### Website

https://biomejs.dev/

### Documentation

https://biomejs.dev/guides/getting-started/

### Integration summary

1. `npm install --save-dev --save-exact @biomejs/biome`
2. `npx @biomejs/biome init`

### Further details

Some notes, as of now biomeJS doesn't *fully* support svelte as of now in the sense that there are some caveats,
https://biomejs.dev/internals/language-support/#html-super-languages-support

Due to it's current support of svelte, I wouldn't mind closing this issue if in your opinion it doesn't seem to fit.

**Comment by manuel3108** [comment]
Looks like this has quite a few caveats, as you noticed. Adding such an adder at this point will only irritate users what they should be choosing. 

Looking at their goals it seems like a good idea to implement that at a later point, when they have better support for svelte files. Just reopen the issue once we get there!

**Comment by MordechaiHadad** [comment]
> Looks like this has quite a few caveats, as you noticed. Adding such an adder at this point will only irritate users what they should be choosing. 
> 
> Looking at their goals it seems like a good idea to implement that at a later point, when they have better support for svelte files. Just reopen the issue once we get there!

That's fair enough, thank you
