### ISSUE TITLE
always write a new line at the end of files

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#458]
### Topic

core

### Description

I just ran the tailwind adders and `postcss.config.js`, `src/app.css`, and `tailwind.config.ts` are missing new lines at the end

### Describe the solution you'd like

Maybe it could be part of the core file writing functionality?

**Comment by manuel3108** [comment]
I think that heavily depends on user-preference. This should already work if you decide to add prettier, then it should consider your local settings inside the prettier config.

**Comment by benmccann** [comment]
For me the main reason to do it isn't really stylistic, cut because it breaks `cat` if you don't. I want to see what changes `svelte-add` made and so often `cat` the new files. Also, GitHub will show an ugly red circle with a line through it if you don't do it.

It seems like we should pick one way or the other vs being inconsistent and having a new line generally works better with tooling. For folks that want to change it they can update their prettier config.
