### ISSUE TITLE
specifying adders from CLI is broken

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#460]
### Topic

cli

### Version

2.3.2

### Expected behavior

this should work:
```
npx svelte-add@latest tailwind
```

### Actual behavior

didn't do anything

**Comment by AdrianGonz97** [comment]
For tailwind, it's actually:
```
npx svelte-add@latest tailwindcss
```

Though, I do see how it can be confusing since it's still going through the process. We should really be validating the specified adders and throwing an error if an invalid adder is provided

**Comment by benmccann** [comment]
Ah, thanks! I think it'd be nice to call that one tailwind. Both Rich and I made that mistake 

But I also agree with validating unknown adders

**Comment by AdrianGonz97** [comment]
I don't think we should rename it because it's called `tailwindcss` everywhere you look, but perhaps we could add an `alias` field to adders?

**Comment by benmccann** [comment]
An alias would work. It's basically full official name of "Tailwind CSS" vs conversationally / colloquially everyone just calls it "Tailwind"
