### ISSUE TITLE
tabs changed to spaces

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#464]
### Topic

mdsvex

### Version

2.3.2

### Expected behavior

leave the tabs in place

it looks like there's a utility function we can use for this now: https://github.com/svelte-add/svelte-add/pull/463#discussion_r1661634219

### Actual behavior

the mdsvex adder changes all of the tabs to spaces in `svelte.config.js`

**Comment by AdrianGonz97** [comment]
i sense that preserving formats is going to be an never ending game of whack-a-mole 😅 

i do want to point out that this is only the case if the user doesn't have `prettier` installed, which is probably an uncommon occurrence. in any case, once #463 is merged, we can reuse that utility function to fix this as well

**Comment by manuel3108** [comment]
I think in the past I made sure that this worked as expected. We might need to try to remove this method for a second to see if this might already fix this.

https://github.com/svelte-add/svelte-add/blob/2f9a963fa826864c8207582b2f8fc3b83a893c44/packages/ast-tooling/index.ts#L81

**Comment by benmccann** [comment]
> i sense that preserving formats is going to be an never ending game of whack-a-mole 😅

I haven't looked at the code that closely, but was hoping if we got the functionality to live in the core functions that it would handle it for most cases

> I think in the past I made sure that this worked as expected.

Yeah, I think that's the case with most of the stuff found in the past day or so. Understandable since there's been a lot of refactoring. I think with some tests hopefully we can avoid having to deal with too many regressions (https://github.com/svelte-add/svelte-add/issues/461)

**Comment by AdrianGonz97** [comment]
> I think in the past I made sure that this worked as expected. We might need to try to remove this method for a second to see if this might already fix this.

You're correct, it is the removal of the locations causing this! Rather than removing `stripAst` altogether, we can just strip a copy of the AST during comparisons, preserving the original tree
