### ISSUE TITLE
[Prettier Adder]: E404 npm ERR! 404 Not Found

### ISSUE THREAD

**Issue by shyakadavis** [svelte-add/svelte-add#489]
### Topic

cli

### Version

N/A

### Expected behavior

When running `pnpm dlx @svelte-add/prettier@latest` or `npx @svelte-add/prettier@latest`, I expected `prettier` addeed to my project.

### Actual behavior

Instead, I am met with these errors:

With `pnpm dlx @svelte-add/prettier@latest`
```
/Users/davis/Library/Caches/pnpm/dlx/4zjxuv3jzwytpnyk2ixns5fe5m/190b7deb780-12873:
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@svelte-add%2Fprettier: Not Found - 404

This error happened while installing a direct dependency of /Users/davis/Library/Caches/pnpm/dlx/4zjxuv3jzwytpnyk2ixns5fe5m/190b7deb780-12873

@svelte-add/prettier is not in the npm registry, or you have no permission to fetch it.

An authorization header was used: Bearer npm_[hidden]
```

With `npx @svelte-add/prettier@latest`:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@svelte-add%2fprettier - Not found
npm ERR! 404
npm ERR! 404  '@svelte-add/prettier@latest' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/davis/.npm/_logs/2024-07-15T19_31_09_281Z-debug-0.log
```

**Comment by manuel3108** [comment]
This syntax is no longer supported. Please consider using 

`pnpm dlx svelte-add prettier`

**Comment by shyakadavis** [comment]
Hey, @manuel3108 

Ah, I see. Thanks. Was misled since I was coming from the docs/website.

I believe a change to the docs is really needed, otherwise someone else might be misled.

Happy to submit a P.R if you're up to it. 🙂
