### ISSUE TITLE
Unable to process 'src/app.css'. Reason: addImports is not a function #12778

### ISSUE THREAD

**Issue by jakubdonovan** [svelte-add/svelte-add#503]
### Topic

adding tailwindcss to a sveltekit project

### Version

 "svelte": "^4.2.7",                                                                                         │

### Expected behavior

`pnpm create svelte@latest testing`
`cd testing`
`pnpm i`
`pnpm dlx svelte-add@latest tailwindcss`

The above should add tailwindcss to the project.

### Actual behavior

 └  Unable to process 'src/app.css'. Reason: addImports is not a function                                         │
                                                           │                                                                                                                      │
                                                           │     Error: Unable to process 'src/app.css'. Reason: addImports is not a function                                     │
                                                           │         at createOrUpdateFiles (file:///Users/aaa/Library/pnpm/store/v3/tmp/dlx-78821/node_modules/.pnpm/@sv│
                                                           │     elte-add+core@2.9.5/node_modules/@svelte-add/core/build/internal.js:361:37)                                      │
                                                           │         at async processInlineAdder (file:///Users/aaa/Library/pnpm/store/v3/tmp/dlx-78821/node_modules/.pnp│
                                                           │     m/@svelte-add+core@2.9.5/node_modules/@svelte-add/core/build/internal.js:14373:33)                               │
                                                           │         at async executePlan (file:///Users/aaa/Library/pnpm/store/v3/tmp/dlx-78821/node_modules/.pnpm/@svel│
                                                           │     te-add+core@2.9.5/node_modules/@svelte-add/core/build/internal.js:14336:28)                                      │
                                                           │         at async executeAdders (file:///Users/aaa/Library/pnpm/store/v3/tmp/dlx-78821/node_modules/.pnpm/@sv│
                                                           │     elte-add+core@2.9.5/node_modules/@svelte-add/core/build/internal.js:14260:5)                                     │
                                                           │         at async executeCli (file:///Users/aaa/Library/pnpm/store/v3/tmp/dlx-78821/node_modules/.pnpm/svelte│
                                                           │     -add@2.3.9/node_modules/svelte-add/build/index.js:64:3)
                                                           
I tried pnpm svelte 4 and svelte 5 (both used to work) but now suffer the same issue. I was able to also reproduce while trying to add it in svelte 4 and 5 projects running on bun.

**Comment by manuel3108** [comment]
@jakubdonovan Thanks for reporting this! We had a problem with our release workflow yesterday, so it did not release all relevant packages. This will be fixed in a minute when the pipeline succeeds! 

Sorry for the inconvenience!

**Comment by jakubdonovan** [comment]
> @jakubdonovan Thanks for reporting this! We had a problem with our release workflow yesterday, so it did not release all relevant packages. This will be fixed in a minute when the pipeline succeeds!
> 
> Sorry for the inconvenience!

I was able to install via pnpm, but keep getting the same error in bun. 

**PNPM**
 jakubdonovan at …/code
 pnpm create svelte@latest pnpm
.../Library/pnpm/store/v3/tmp/dlx-87835  |   +6 +
.../Library/pnpm/store/v3/tmp/dlx-87835  | Progress: resolved 6, reused 6, downloaded 0, added 6, done

create-svelte version 6.3.4

┌  Welcome to SvelteKit!
│
◇  Which Svelte app template?
│  Skeleton project
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◇  Select additional options (use arrow keys/space bar)
│  Add ESLint for code linting, Add Prettier for code formatting, Add Playwright for browser testing, Try the Svelte 5 preview (unstable!)
│
└  Your project is ready!

Install more integrations with:
  npx svelte-add

Next steps:
  1: cd pnpm
  2: pnpm install
  3: git init && git add -A && git commit -m "Initial commit" (optional)
  4: pnpm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat

 jakubdonovan at …/code
 cd pnpm

 jakubdonovan at …/pnpm
 pnpm i
 WARN  3 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6, rimraf@2.7.1
Packages: +219
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 256, reused 219, downloaded 0, added 219, done

devDependencies:
+ @playwright/test 1.45.3
+ @sveltejs/adapter-auto 3.2.2
+ @sveltejs/kit 2.5.18
+ @sveltejs/vite-plugin-svelte 3.1.1
+ @types/eslint 9.6.0
+ eslint 9.7.0
+ eslint-config-prettier 9.1.0
+ eslint-plugin-svelte 2.43.0
+ globals 15.8.0
+ prettier 3.3.3
+ prettier-plugin-svelte 3.2.6
+ svelte 5.0.0-next.198
+ svelte-check 3.8.4
+ typescript 5.5.4
+ typescript-eslint 8.0.0-alpha.54
+ vite 5.3.4

 WARN  Issues with peer dependencies found
.
└─┬ @sveltejs/vite-plugin-svelte 3.1.1
  └─┬ svelte-hmr 0.16.0
    └── ✕ unmet peer svelte@"^3.19.0 || ^4.0.0": found 5.0.0-next.198

Done in 8.4s

 jakubdonovan at …/pnpm
 pnpm dlx svelte-add@latest tailwind
Packages: +5
+++++
Progress: resolved 5, reused 5, downloaded 0, added 5, done
Invalid adder selected: tailwind

 jakubdonovan at …/pnpm
 pnpm dlx svelte-add@latest tailwindcss
Packages: +5
+++++
Progress: resolved 5, reused 5, downloaded 0, added 5, done
svelte-add version 2.3.10

┌  Welcome to Svelte Add!
│
◇  Do you want to use typography plugin?
│  No
│
◇  Successfully installed dependencies
│
◇  Successfully formatted modified files
│
└  You're all set!

**BUN**
 jakubdonovan at  ~
 cd bun

 jakubdonovan at …/bun
 bun i
bun install v1.1.20 (ae194892)
warn: incorrect peer dependency "svelte@5.0.0-next.198"

+ @playwright/test@1.45.3
+ @sveltejs/adapter-auto@3.2.2
+ @sveltejs/kit@2.5.18
+ @sveltejs/vite-plugin-svelte@3.1.1
+ @types/eslint@8.56.11 (v9.6.0 available)
+ eslint@9.7.0
+ eslint-config-prettier@9.1.0
+ eslint-plugin-svelte@2.43.0
+ globals@15.8.0
+ prettier@3.3.3
+ prettier-plugin-svelte@3.2.6
+ svelte@5.0.0-next.198
+ svelte-check@3.8.4
+ tslib@2.6.3
+ typescript@5.5.4
+ typescript-eslint@8.0.0-alpha.54
+ vite@5.3.4

220 packages installed [4.80s]

Blocked 1 postinstall. Run `bun pm untrusted` for details.

 jakubdonovan at …/bun
 bun pm trust --all
bun pm trust v1.1.20 (ae194892)

./node_modules/svelte-preprocess @5.1.4
 ✓ [postinstall]: echo \"[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...\"

 1 script ran across 1 package [54.00ms]

 jakubdonovan at …/bun
 bun i
bun install v1.1.20 (ae194892)

Checked 223 installs across 258 packages (no changes) [83.00ms]

 jakubdonovan at …/bun
 bunx svelte-add@latest tailwindcss
svelte-add version 2.3.9

┌  Welcome to Svelte Add!
│
◇  Do you want to use typography plugin?
│  No
└  Unable to process 'src/app.css'. Reason: addImports is not a function

Error: Unable to process 'src/app.css'. Reason: addImports is not a function
    at createOrUpdateFiles (file:///private/tmp/bunx-501-svelte-add@latest/node_modules/@svelte-add/core/build/internal.js:361:37)
    at async processInlineAdder (file:///private/tmp/bunx-501-svelte-add@latest/node_modules/@svelte-add/core/build/internal.js:14373:33)
    at async executePlan (file:///private/tmp/bunx-501-svelte-add@latest/node_modules/@svelte-add/core/build/internal.js:14336:28)
    at async executeAdders (file:///private/tmp/bunx-501-svelte-add@latest/node_modules/@svelte-add/core/build/internal.js:14260:5)
    at async executeCli (file:///private/tmp/bunx-501-svelte-add@latest/node_modules/svelte-add/build/index.js:64:3)
    
    
   
   Any ideas?

**Comment by AdrianGonz97** [comment]
That's a caching issue. Notice how the version is still `2.3.9` while the current version is `2.3.10`. You'll need to purge the global cache from bun:
`bun pm cache rm`

see: https://bun.sh/docs/cli/pm

**Comment by manuel3108** [comment]
Yeah, we had such things happening before. PNPM apparently has less strict caching and correctly downloaded the newest version

**Comment by jakubdonovan** [comment]
> Yeah, we had such things happening before. PNPM apparently has less strict caching and correctly downloaded the newest version

That did it, appreciate it!
