### ISSUE TITLE
How to add bootstrap?

### ISSUE THREAD

**Issue by JohnKiller** [svelte-add/svelte-add#549]
### Topic

Bootstrap removed from latest version

### Description

Hi, the latest version removed bootstrap support. What's the "official" way to install it from now on? I know JS is broken and there are projects that provides Svelte components, but I just want the SCSS.

Thanks

**Comment by manuel3108** [comment]
For the time being, you can still use `svelte-add@2.6.2`.
But keep in mind, there are multiple reasons why we have removed those adders. One of them is that both the bootstrap and bulma adders in their sass/scss versions were painfully slow during dev start, but also on later hot reloads. 

Without trying it out by hand, this [guide](https://getbootstrap.com/docs/5.3/getting-started/vite/#setup) seems like it should work, if you have some basic knowledge about the kit vite integration.

**Comment by JohnKiller** [comment]
Yeah I've noticed it too that build time is impacted.

I'm tempted to try Tailwind however I've been using bootstrap since forever and I'm also switching to Svelte for a new project so changing also the css library would mean basically throwing away everything I know about web development...

Thanks for your input, I'll do some research.

**Comment by manuel3108** [comment]
Totally understand that. Another point is the usage and support we have experiencend in the past. [Here](https://npmcharts.com/compare/tailwindcss,bulma,bootstrap) are the relevant download numbers for the three relevant libraries
