### ISSUE TITLE
darkMode not working properly

### ISSUE THREAD

**Issue by psyCodelist** [svelte-add/svelte-add#76]
`Hi,`

followed instructions as mentioned in the docs. Worth mentioning that I used **tailwindcss/jit**

but when I add dark:bg-gray-800  in global.css I get:

CssSyntaxError: /Users/nima/DeltaStream/src/global.css:8:5: The `dark:bg-gray-800` class does not exist. If `dark:bg-gray-800` is a custom class, make sure it is defined within a `@layer` directive.

here is my global.css:
`/* Write your global styles here, in PostCSS syntax */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  body {
    @apply bg-blue-50 dark:bg-gray-800;
  }
}
`

**Comment by kotx** [comment]
Hi @psyCodelist, would you mind sharing your configuration? I have this issue too.
