### ISSUE TITLE
Add windicss

### ISSUE THREAD

**Issue by Evertt** [svelte-add/svelte-add#8]
Here's the docs for it: https://windicss.netlify.app/guide/svelte.html#sveltekit

**Comment by babichjacob** [comment]
My intention if I ever get around to this is integrating it as an option to `svelte-add/tailwindcss`, by the way

**Comment by babichjacob** [comment]
There is now Tailwind JIT support in [`svelte-add/tailwindcss`](https://github.com/svelte-add/tailwindcss) which is close, right?

**Comment by Evertt** [comment]
Yeah I'd say so. I'm using Tailwind JIT as we speak and it's great and it was much easier to integrate into my existing projects than windicss was. So for me windicss support isn't really necessary anymore. :-)

**Comment by babichjacob** [comment]
Gonna leave this open since WindiCSS has other features Tailwind JIT doesn't.

**Comment by Evertt** [comment]
Like what? I hope those features will just be merged into the original
tailwind, because it'd suck to have 2 similar, but slightly different
libs. 😅

>

**Comment by babichjacob** [comment]
My implementation of the Windi CSS adder is being removed. 

**After** the `svelte-add` rewrite, someone who can be trusted to set it up correctly and maintain it can contribute it to this repository.

**Comment by manuel3108** [comment]
Closing this as WindiCSS is in the process of sunsetting. They recommend using other css framework for new projects: https://windicss.org/posts/sunsetting.html
