### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by GrygrFlzr** [svelte-add/svelte-add#92]
## Confirming base tailwind works
1. Setup:
```sh
# selected Y for typescript, CSS for styles
npm init svelte@next

# said yes to update node dependencies
npx apply svelte-add/postcss

# said yes to update node dependencies
npx apply svelte-add/tailwindcss

npm install
npm update
```
2. I also manually added tailwind to the `postcss.config.cjs` since I'm on Windows with CRLF endings and svelte-add/tailwindcss#4 is in effect:
```js
const tailwindcss = require("tailwindcss");
const autoprefixer = require("autoprefixer");
const cssnano = require("cssnano");

const mode = process.env.NODE_ENV;
const dev = mode === "development";

module.exports = {
  plugins: [
    tailwindcss,
    autoprefixer,

    !dev &&
      cssnano({
        preset: "default",
      }),
  ],
};
```
3. Use the custom snowpack config as per svelte-add/tailwindcss#7.
4. Confirm that sort-of-out-of-the-box experience works.

## Testing class-based dark mode
1. Enable class dark mode in `tailwind.config.cjs` and comment out all purging, to rule it out as a potential variable:
```
module.exports = {
  darkMode: "class",
  //   purge: {
  //     ...
  //    },
  // ...
};
```
2. Update `index.svelte` to apply the `dark` class:
```html
<main class="dark">
```
3. Update `Counter.svelte` to apply a background on dark mode:
```svelte
<button on:click={increment} class="dark:bg-gray-900">
```
4. `npm run dev` to observe that the classes are on the element, but no change has occured, and no dark-mode CSS rules are being applied/overridden (you can use the inspector to check this).
5. Undo step 3 and change the button style with `@apply` instead:
```css
  button {
    /* ... */
    @apply dark:bg-gray-900;
  }
```
An error will appear:
```
Build Error: @snowpack/plugin-svelte
CssSyntaxError: C:\Users\GrygrFlzr\Documents\projects\tw-test\src\components\Counter.svelte:15:12: The `dark:bg-gray-900` class does not exist, but `2xl:bg-gray-900` does. If you're sure that `dark:bg-gray-900` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  13 |     @apply w-48;
  14 |     font-variant-numeric: tabular-nums;
> 15 |     @apply dark:bg-gray-900;
     |            ^
  16 |   }
  17 | 
```

## Testing media-based dark mode
Repeat the above section, except with `darkMode: "media"`, and setting the browser preference to dark mode.

## Other attempts
I've also attempted both the class and media modes with explicitly adding support for the dark `backgroundColor` variant, to no avail:
```js
// tailwind.config.cjs
module.exports = {
  // ...
  variants: {
    extend: {
      backgroundColor: ['dark']
    }
  }
}
```

**Comment by kotx** [comment]
I have this same problem even after following the steps posted above.

**Comment by bryanmylee** [comment]
For what it's worth, I've written a TailwindCSS [plugin](https://github.com/bryanmylee/tailwindcss-global-dark) to introduce a `gdark` variant that creates a dark mode class selector with `:global(.dark)` that works with CSS modules and Svelte scoped stylesheets.

Instead of `dark:bg-gray-800` in your @apply, you can use `gdark:bg-gray-800`.

**Comment by justingolden21** [comment]
Still having this issue in July 2022, been facing this for over a year, still using `:global(.dark)` and doubling the line count of every single css file.

**Comment by justingolden21** [comment]
Doing something similar to
```css
<style lang="postcss" global>
    :local(button) {
        @apply dark:text-green-100 dark:bg-green-800;
    }
</style>
```
Worked for me, but I'm still a little confused on `global` vs `:global` vs `:local`. Seems like `global` is svelte preprocess and the others are postcss, and having both `global` and `:local` make it so the styles are local but reading the global styles for dark mode as a class?

**Comment by hugotox** [comment]
dark mode still doesn't work on a barebones install. Following the official [sveltekit instructions](https://tailwindcss.com/docs/guides/sveltekit) and [manual dark mode instructions ](https://tailwindcss.com/docs/dark-mode#supporting-system-preference-and-manual-selection)

**Comment by manuel3108** [comment]
I did try to reproduce this issue sometime last week but was unable to. If this is still happening to you, please open a new issue, and add your command output (including your commands) and environment info.

Thanks!
