### ISSUE TITLE
Tailwind's classes do not work in html elements (SvelteKit v1.0.0-next.102)

### ISSUE THREAD

**Issue by pablohgm** [svelte-add/svelte-add#94]
Hi, I was trying to get a clean installation of svelte-kit and tailwind
I did
```
npm init svelte@next appName
npx svelte-add tailwindcss
npm i
```

The installation is ok, `@apply` styles works as expected, but when I tried to use tailwind's classes in the elements, the styles do not work, for example:
`<p class='text-red-50'>test</p>`

FYI
```
✔ Which Svelte app template? › R/ SvelteKit demo app
✔ Use TypeScript? … R/ No
✔ Add ESLint for code linting? … R/ Yes
✔ Add Prettier for code formatting? … R/ Yes
```

**Comment by babichjacob** [comment]
> Hi am using svelte and I am facing the same issue. Thee's an app.js file and it is imported in the main.js file. Commands I used: npx degit sveltejs/tamplate myproject yarn npx svelte-add@latest tailwindcss yarn

@28JayG `svelte-add` doesn't support Rollup or webpack. If you're starting a new Svelte project, use Vite: https://github.com/svelte-add/svelte-add#-support-for-svelte-with-webpack-or-rollup

**Comment by emmalu** [comment]
> ```
> class="max-w-3xl mx-auto"
> ```

**Comment by MentalGear** [comment]
Found out that I had to use JIT mode, else classes in sveltekit weren't correctly updating.

```js
	mode: 'jit', // nneeded, else classes not correctly updating in sveltekit

```

**Comment by babichjacob** [comment]
> Found out that I had to use JIT mode, else classes in sveltekit weren't correctly updating.
> 
> ```js
> 	mode: 'jit', // nneeded, else classes not correctly updating in sveltekit
> ```

@MentalGear This is really shocking, because the Tailwind CSS adder has been using Tailwind version 3 by default for a couple months, where `mode: "jit"` has no effect. Are you sure you used the latest version of `svelte-add` when adding Tailwind: `npx --yes svelte-add@latest tailwindcss`?

**Comment by MentalGear** [comment]
Sorry for the confusion @babichjacob . I found this issue via google and no I wasn't using svelte-add!
